### ISSUE TITLE
有关断点调试的问题

### ISSUE THREAD

**Issue by zey28** [PanJiaChen/vue-admin-template#100]
你好,请问为什么在用chrom断点调试的时候,对于源码中从外部导入的变量为什么都显示无法找到引用的问题呢,望解惑 ,ReferenceError: store is not defined

**Comment by PanJiaChen** [comment]
都提示了你`store is not defined`

**Comment by zey28** [comment]
但是console.log 打印日志可以打印出来啊,只是断点的时候无法显示

**Comment by zey28** [comment]
好像所有通过import 导入的变量都是这样, 通过函数传入的变量就可以显示出来

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-admin-template/blob/cc636a4ccdd4305c1c03c99d27ee82fd1621cd0e/.babelrc#L4

这个原因，没有好的办法。你可以看 `chrome scope`里面的信息。
