### ISSUE TITLE
页面返回不刷新？

### ISSUE THREAD

**Issue by waittingbar** [PanJiaChen/vue-admin-template#113]
子页面中，浏览器返回到父页面时，页面不刷新。再从父页面跳到子页面也不能刷新页面. 我测试了 完整版那个项目是可以 刷新的。 还有就是 this.$route.push 是通过name 匹配的吗，怎么不是path呢？

**Comment by PanJiaChen** [comment]
请具体一点描述

**Comment by waittingbar** [comment]
就是 我从列表页面 通过 this.$router.push({ path: '/goods/skuManage/editSku', name: '编辑sku', query: { skuId: 123, skuComId: 666 }}); 跳转到 编辑详情页面，在详情页通过传递的参数查询详情。但是现在 只有首次进入这个页面，created 中的方法才会调用。当我通过浏览器返回按钮退到列表页面，列表页面没有刷新，重新进入一行的编辑页面，所带的参数不同，页面也没有刷新。

**Comment by PanJiaChen** [comment]
浏览器返回按钮不刷新这是正常现象。

**Comment by waittingbar** [comment]
关键是返回再次进入那个页面的时候，created中的方法也没有调用。

**Comment by PanJiaChen** [comment]
没能重现，请提供最小可重现demo。而且请确定自己没用使用keep-alive。

**Comment by waittingbar** [comment]
sorry 忘记了这个issue，之前找到问题了，是因为我错误的使用<keep-alive>将 <router-view></router-view> 包裹起来了，所以导致不刷新。
