### ISSUE TITLE
login登陆界面出现问题

### ISSUE THREAD

**Issue by dawayway** [PanJiaChen/vue-admin-template#127]
裤衩哥，login登陆界面出现问题，我试了好几次都不行，是不是easy-mock出问题了，

**Comment by tandrew** [comment]
I believe the service is down ... Cannot reach easy-mock.com at all.

![image](https://user-images.githubusercontent.com/8017453/42465885-98b6a52c-83ad-11e8-833e-2a58026a4c3e.png)

**Comment by PanJiaChen** [comment]
`easy-mock`的确有些不稳定，我考虑一下是不是要换一个mock源。

**Comment by cxxly** [comment]
无法登陆 timeout of 5000ms exceeded

**Comment by newbeekk** [comment]
> 无法登陆 timeout of 5000ms exceeded

我也是这个错误，裤衩哥，这是怎么回事啊

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-admin-template/issues/241
