### ISSUE TITLE
permission-control 分支

### ISSUE THREAD

**Issue by ShingLi** [PanJiaChen/vue-admin-template#155]
看readme.md 上说这个分支是可以根据用户角色动态生成路由，我的理解是不同的账号进去看到的视图是不同的，但是现在只有admin 能进入 。 看代码里面也只有admin 怎么体现出 动态生成可访问的路由表?

**Comment by glfdd** [comment]
我使用editor和admin登录之后界面是一样的，没有实现readme中所说的动态路由，请问是什么原因。有人解决吗
