### ISSUE TITLE
build打包之后样式全部消失

### ISSUE THREAD

**Issue by wywsoor** [PanJiaChen/vue-admin-template#157]

**Comment by PanJiaChen** [comment]
请用正确的姿势提问。

**Comment by wywsoor** [comment]
![tim 20180827122539](https://user-images.githubusercontent.com/26341601/44640466-5e0fac80-a9f4-11e8-8805-c115ab327b07.png)
build 之后样式就干脆消失了

**Comment by wywsoor** [comment]
这样够清楚吧
