### ISSUE TITLE
bulid 之后样式混乱

### ISSUE THREAD

**Issue by wywsoor** [PanJiaChen/vue-admin-template#158]
![tim 20180827122539](https://user-images.githubusercontent.com/26341601/44640553-ea21d400-a9f4-11e8-9058-3712a1861962.png)
zg这样该清楚了吧

**Comment by PanJiaChen** [comment]
你看控制台有没有报错，有没有加载必要的css

**Comment by wywsoor** [comment]
所有浏览器都有问题 控制台没有报错 一个style 都没有

**Comment by yangdengcheng** [comment]
需要改配置文件的，把assetsPublicPath改成“./”即可

**Comment by wywsoor** [comment]
并不好使

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-admin-template/#/

线上访问地址有这问题么？

**Comment by wywsoor** [comment]
线上地址没有问题 ，有没有可能是我引入了一个js造成的 ，为了搞一个配置文件单独在index。html里引用了一个js

**Comment by wywsoor** [comment]
线上地址没问题   
出现  Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:8888/static/css/chunk-libs.fd5c6263.css".  这种warning

**Comment by PanJiaChen** [comment]
那请自行将报错谷歌一下。感觉不是本项目的问题。

你试试本地启一个服务有没有问题。

**Comment by wywsoor** [comment]
找到问题了，貌似是我用 nodejs 写的web服务貌似有点问题，换了一个golang的服务就好了

**Comment by wywsoor** [comment]
感谢大佬帮助！！！
