### ISSUE TITLE
打开标签页样式问题

### ISSUE THREAD

**Issue by movesan** [PanJiaChen/vue-admin-template#162]
你好，现模板与vue-element-admin打开标签页的样式不一致，请问如果想用vue-element-admin中打开标签页滑动渐进的效果需要做哪些配置的修改呢？感谢

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-admin-template/commit/a91f687c2dcb9add0861943c910d739c8d515e66

**Comment by movesan** [comment]
感谢 @PanJiaChen
