### ISSUE TITLE
访问后台API接口问题

### ISSUE THREAD

**Issue by movesan** [PanJiaChen/vue-admin-template#163]
你好，看了一下你写的文档介绍，目前修改如下：
config/index.js文件
   proxyTable: {
      '/api': {
        target: 'http://localhost:8000',
        pathRewrite: {'^/api' : ''}
      }
    }

config/dev.env.js文件
module.exports = merge(prodEnv, {
  NODE_ENV: '"development"',
  BASE_API: '"https://127.0.0.1:8000"',
  // BASE_API: '"https://easy-mock.com/mock/5950a2419adc231f356a6636/vue-admin"',
})

api请求文件
export function fetchList(query) {
  return request({
    url: '/deeplearning/test',
    method: 'get',
    params: query
  })
}

前端请求时，浏览器debug调试显示请求地址为 https://127.0.0.1:8000/api/deeplearning/test，
状态为：(failed)，现在主要有两个疑问：
1.config/dev.env.js设置的BASE_API 与config/index.js中代理设置的目标路径会有冲突吗？
2.怎样才能走到config/index.js中代理，目前看来貌似代理没有生效呢？

看了很多相关issue也没有找到争取的解决方法，也花了很多功夫，所以特来请教一下，感谢

**Comment by movesan** [comment]
@PanJiaChen 感谢指点，现在已将 BASE_API 修改，此时的浏览器请求为 
http://localhost:8080/deeplearning/test/

api请求文件
export function fetchList(query) {
return request({
url: '/api/deeplearning/test',
method: 'get',
params: query
})
}

说明已经走了proxyTable，但现在报错为 404，显然已经将请求url中的api去掉了，现在看来还是访问的
前端而没有请求后台；
后端地址http://127.0.0.1:8000/deeplearning/test/正常，可以返回数据，
请问还需要改哪些配置吗？

**Comment by PanJiaChen** [comment]
404就是自己的问题了。

**Comment by movesan** [comment]
postman访问正常，浏览器也可以直接访问返回数据，现在走了代理之后F12请求地址是
http://localhost:8080/deeplearning/test/
8080是我前端项目的端口号，8000才是我服务端口，但是代理的话是不是不会改变域名和端口的显示，
如果我点击按钮，正确的显示应该是后端端口号+路径吗？
![image](https://user-images.githubusercontent.com/16206967/44770335-5427ae00-ab9a-11e8-8c8f-f199ca779e63.png)

**Comment by movesan** [comment]
@PanJiaChen 可以再帮忙看下吗，或者作者有没有自己的涉及跨域的项目和demo借鉴一下哈，感谢

**Comment by PanJiaChen** [comment]
https://marskid.net/2018/01/14/webpack-devserver-proxy/

请自行研究，跨域问题多半是自己配置问题，可能性太多了，提供不了帮助。

**Comment by movesan** [comment]
@PanJiaChen 好的，如果不是模板的问题，那应该是我自己的问题，我在研究一下，再次感谢

**Comment by IntPassion** [comment]
请问楼主问题解决了吗？我也遇到了相同的问题

**Comment by movesan** [comment]
@IntPassion 在此项目模板下没有解决，之后由于一些原因又转到其他模板了，不过也同样遇到了跨域问题，后来是通过nginx 跳转解决的，希望对你有帮助
