### ISSUE TITLE
icon 不显示

### ISSUE THREAD

**Issue by zrleo** [PanJiaChen/vue-admin-template#164]
![image](https://user-images.githubusercontent.com/21098426/44776845-9dccc480-abab-11e8-8841-9992dd95358e.png)
在侧边栏 icon无法显示

**Comment by PanJiaChen** [comment]
你确定有 form 这个 icon么。。

**Comment by zrleo** [comment]
知道原因了 少装了一个包 谢谢大神 微信打赏了 非常感谢

**Comment by Ale-cc** [comment]
> 知道原因了 少装了一个包 谢谢大神 微信打赏了 非常感谢

少安装了什么包？
