### ISSUE TITLE
运行 npm run build：report报错

### ISSUE THREAD

**Issue by wywsoor** [PanJiaChen/vue-admin-template#166]
![tim 20180830181409](https://user-images.githubusercontent.com/26341601/44845629-a6db9580-ac80-11e8-8e54-8b4e2921b8af.png)
buzh不知道这个是啥作用不是打包？

**Comment by Dinrer** [comment]
用这个命令 npm run build --report，papackage.json里配的命令的有问题

**Comment by PanJiaChen** [comment]
这个命令作用是打包并生产 webpack 打包结果的依赖图。

![image](https://user-images.githubusercontent.com/8121621/44888831-b5b85b80-ad05-11e8-9ca3-bbca2ac20deb.png)

**Comment by wywsoor** [comment]
问题是是我运行方式不对吗为啥报错
