### ISSUE TITLE
能否支持布局可控

### ISSUE THREAD

**Issue by mcmf** [PanJiaChen/vue-admin-template#167]
如果业务简单 可能不需要顶部菜单 只需要左侧菜单就能实现业务。
![image](https://user-images.githubusercontent.com/19700237/44941454-6a1eb400-add0-11e8-90eb-5b9f9490ca3f.png)

如果业务复杂 需要顶部菜单点击后列出左侧菜单
![image](https://user-images.githubusercontent.com/19700237/44941466-8e7a9080-add0-11e8-8f65-a3d9e44c6738.png)

能否全局有个可控切换

**Comment by PanJiaChen** [comment]
不准备支持顶部菜单。

**Comment by PanJiaChen** [comment]
可关注 该问题 https://github.com/PanJiaChen/vue-element-admin/issues/1035

**Comment by mcmf** [comment]
![image](https://user-images.githubusercontent.com/19700237/45016919-be3bc980-b058-11e8-9c84-ae037812d411.png)

**Comment by PanJiaChen** [comment]
恩是的，效果应该和 https://github.com/ant-design/ant-design-pro 差不多

**Comment by Awezome** [comment]
我也找了半天没有相关的参数，就自己搞了一个。https://github.com/Awezome/vue-admin-topmenu
![demo](https://raw.githubusercontent.com/Awezome/vue-admin-topmenu/master/preview.png)
