### ISSUE TITLE
npm run build报错

### ISSUE THREAD

**Issue by esc95** [PanJiaChen/vue-admin-template#170]
![image](https://user-images.githubusercontent.com/22993580/45071932-3bc01200-b10b-11e8-8813-64e9d1f3c438.png)
20 error code ELIFECYCLE
21 error errno 1
22 error vue-admin-template@3.8.0 build: `node build/build.js`
22 error Exit status 1
23 error Failed at the vue-admin-template@3.8.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

真的不知道怎么办了

**Comment by esc95** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle vue-admin-template@3.8.0~prebuild: vue-admin-template@3.8.0
6 info lifecycle vue-admin-template@3.8.0~build: vue-admin-template@3.8.0
7 verbose lifecycle vue-admin-template@3.8.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle vue-admin-template@3.8.0~build: PATH: C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\文件夹\vue\vue-admin-template\node_modules\.bin;C:\Ruby25-x64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;D:\Program Files\Microsoft VS Code\bin;C:\Users\Administrator\AppData\Roaming\npm;d:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\bin
9 verbose lifecycle vue-admin-template@3.8.0~build: CWD: E:\文件夹\vue\vue-admin-template
10 silly lifecycle vue-admin-template@3.8.0~build: Args: [ '/d /s /c', 'node build/build.js' ]
11 silly lifecycle vue-admin-template@3.8.0~build: Returned: code: 1  signal: null
12 info lifecycle vue-admin-template@3.8.0~build: Failed to exec build script
13 verbose stack Error: vue-admin-template@3.8.0 build: `node build/build.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid vue-admin-template@3.8.0
15 verbose cwd E:\文件夹\vue\vue-admin-template
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error vue-admin-template@3.8.0 build: `node build/build.js`
22 error Exit status 1
23 error Failed at the vue-admin-template@3.8.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]



错误日志

**Comment by PanJiaChen** [comment]
一个webpack 第三方插件的问题，我来处理一下。
