### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by qietuniu** [PanJiaChen/vue-admin-template#172]
选择了权限的分支，新增了tab的功能，打包之后报错
 compilation.hooks.htmlWebpackPluginAlterAssetTags.tap(PLUGIN, alterAssetTags);
                                                        ^

TypeError: Cannot read property 'tap' of undefined

**Comment by 307590317** [comment]
删了 node_modules 和 package-lock.json 重新安装一下。 @qietuniu

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-admin-template/issues/170
