### ISSUE TITLE
Vue + typescript version admin template

### ISSUE THREAD

**Issue by Armour** [PanJiaChen/vue-admin-template#173]
Hi, I just created a vue + typescript version admin template [here](https://github.com/Armour/vue-typescript-admin-template) and it fixed several existing bugs, I'll send PRs for those bug fixes later, maybe you can add this repo to the related project links section, thanks! :)

你好0.0 我最近参考这个repo写了个vue+typescript版本的admin template (基于vue-cli 3), 也顺便fix了一些小bug，我倒时候可以再发PR给你，或许可以考虑把我的这个repo加到related project下面？ 这样可能会对喜欢用vue+typescript的人有所帮助:) 蟹蟹hhh  (我如果有时间可以考虑慢慢的把那个更大的vue-elment-admin也转成typescript的 有什么意见也可以提给我～

**Comment by PanJiaChen** [comment]
Welcome to submit pr
I opened a new branch [typescript](https://github.com/PanJiaChen/vue-admin-template/tree/typescript)

**Comment by crashsol** [comment]
太好了，正想用这个

**Comment by Armour** [comment]
#174
