### ISSUE TITLE
偶爾EASY-MOCK會不能請求

### ISSUE THREAD

**Issue by Lin-Kyle** [PanJiaChen/vue-admin-template#175]
https://easy-mock.com/mock/5950a2419adc231f356a6636/vue-admin/user/login
我登陸的時候會超時timeout of 5000ms exceeded，
直接訪問的時候輸出Sometimes You Just Have to Slow Down.即使進去了也是發不出請求

這個不是項目問題，就是想問問平時遇到的話怎麽解決，我看文檔沒發現這種事

**Comment by PanJiaChen** [comment]
主要是 `easy-mock` 不稳定导致的。暂时也没找到什么好的替代方案。

**Comment by ganpengyu** [comment]
> 主要是 `easy-mock` 不稳定导致的。暂时也没找到什么好的替代方案。

请问怎么暂时关闭 Mock ？

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-admin-template/issues/241
