### ISSUE TITLE
Invalid value for option "computed": expected an Object, but got Function.

### ISSUE THREAD

**Issue by qietuniu** [PanJiaChen/vue-admin-template#179]
修改路由会出现这个提示，无法定位是哪的问题
`import Vue from 'vue'
import Router from 'vue-router'

Vue.use(Router)

import Layout from '../views/layout/Layout'

export const constantRouterMap = [
  { path: '/login', component: () => import('@/views/login/index'), hidden: true },
  { path: '/404', component: () => import('@/views/404'), hidden: true },
  {
    path: '/',
    component: Layout,
    redirect: '/dashboard',
    name: 'Dashboard',
    hidden: true,
    children: [{
      path: 'dashboard',
      component: () => import('@/views/home/index')
    }]
  },
  {
    path: '/',
    component: Layout,
    redirect: '/home',
    name: 'Home',
    hidden: true,
    meta: { title: '首页' },
    children: [{
      path: 'home',
      component: () => import('@/views/home/index')
    }]
  },
  {
    path: '/system',
    component: Layout,
    redirect: '/system/billApproval',
    name: 'System',
    meta: {
      title: '系统设置',
      icon: 'nested'
    },
    children: [
      {
        path: 'billApproval',
        component: () => import('@/views/system/billApproval'),
        name: 'BillApproval',
        meta: { title: '单据审批配置' }
      },
      {
        path: 'billFlow',
        name: 'BillFlow',
        component: () => import('@/views/system/billFlow'),
        meta: { title: '单据审批流程' }
      }
    ]
  },
  {
    path: '/sale',
    component: Layout,
    redirect: '/sale/billApproval',
    name: 'Sale',
    meta: {
      title: '销售管理',
      icon: 'nested'
    },
    children: [
      {
        path: 'shopManage',
        component: () => import('@/views/sale/shopManage'),
        name: 'ShopManage',
        meta: { title: '商铺管理' }
      },
      {
        path: 'shop',
        component: () => import('@/views/sale/shopManage'),
        name: 'Shop',
        meta: { title: '商铺' }
      }
    ]
  },
  { path: '*', redirect: '/404', hidden: true }
]

export default new Router({
  // mode: 'history', //后端支持可开
  scrollBehavior: () => ({ y: 0 }),
  routes: constantRouterMap
})
`

**Comment by PanJiaChen** [comment]
报错已经很明确了。请自行检索关键词解决。
