### ISSUE TITLE
vue代码稍微有点问题时，浏览器内存就死循环增长

### ISSUE THREAD

**Issue by davidvon** [PanJiaChen/vue-admin-template#180]
请问有没有遇到： vue代码开发时，代码稍微有点问题时，浏览器内存就死循环增长？希望能收到回复， 谢谢！

**Comment by PanJiaChen** [comment]
请用正确的姿势提问？让我猜你你的问题？

**Comment by davidvon** [comment]
问题解决了。在errorLog模块自己写出bug导致死循环了。谢谢
