### ISSUE TITLE
跨域错误

### ISSUE THREAD

**Issue by xiaozhanghui** [PanJiaChen/vue-admin-template#182]
![7c651c7c-ac32-7e36-0f6a-49f0e979016f](https://user-images.githubusercontent.com/23646391/45480819-7b76a180-b77c-11e8-8c3c-55a8f7ad1553.jpg)
safari报错
Failed to load resource: Request header field Content-Type is not allowed by Access-Control-Allow-Headers.
chrome正常

**Comment by PanJiaChen** [comment]
跨域问题请自行网上搜解决方案。
