### ISSUE TITLE
关于请求发送与拦截

### ISSUE THREAD

**Issue by VonJane** [PanJiaChen/vue-admin-template#183]
前辈您好，我目前建了一个项目是基于template的，在引用了原项目的请求插件后，发现无法发送正常的post请求，原因是模板里的拦截器全部拦截到了，请问我该怎么做才能让请求正常发送？附上项目地址[https://github.com/VonJane/jane-sys-vue](url)   对了我要发送请求的页面是在form文件夹下面。

**Comment by PanJiaChen** [comment]
拦截器拦截？

在发请求这里并没有做什么特别处理。

**Comment by VonJane** [comment]
可是我在发送请求时报错，post defined，我把request.js里的拦截器注释掉就可以进入我的后台。。我不太懂是为什么？

**Comment by VonJane** [comment]
是的，response与request拦截器。我确定我的路径没有问题，配置了proxyble，就是webpack哪个 我之前玩了个别的项目同样配置就可以进入后台debug，您可以看一眼我目前的项目文件。

**Comment by PanJiaChen** [comment]
你自己network里面看一下不就知道了，请求发出去了，后端问题，没法出去，前端问题。
