### ISSUE TITLE
如何引入echarts模块？

### ISSUE THREAD

**Issue by salamander-mh** [PanJiaChen/vue-admin-template#187]
pakcage.json加入了echarts了，依赖也装了，然后代码中加入（按vue-element-admin里的写）
```
import echarts from 'echarts'
require('echarts/theme/macarons') 
```
但是报错了，是不是webpack中我需要配置一下呢？

**Comment by PanJiaChen** [comment]
你报错导倒是吧报错提出来啊。

**Comment by salamander-mh** [comment]
就写了一个方法初始化echart对象：
```
initChart() {
     this.chart = echarts.init(document.getElementById('chart'), 'macarons');
},
```
发现echarts未定义
![_006](https://user-images.githubusercontent.com/16663435/45727891-3927e700-bbf8-11e8-97a2-bfa95ea38b8a.png)

**Comment by PanJiaChen** [comment]
debug echarts 未引入 是 webpack 打包的问题(暂时无解)。

你应该搜 echarts getAttribute 这个问题。

**Comment by salamander-mh** [comment]
我把方法放到created钩子里了，这个时候chart DOM还不存在
没好好看文档
