### ISSUE TITLE
最新版的sidebar是在新的z-index中的

### ISSUE THREAD

**Issue by salamander-mh** [PanJiaChen/vue-admin-template#190]
![image](https://user-images.githubusercontent.com/16663435/45953774-af37ae00-c03d-11e8-88d6-dced3fb7769f.png)  
用了以前的样式，新版本看到了侧边栏是在新的一层里的，请问把哪里的样式调整一下，可以做到新版本的样子？

**Comment by PanJiaChen** [comment]
我不知道你所说的老版本是哪个版本。

> 新版本看到了侧边栏是在新的一层里的

这段话也不是很能理解。

调整的话只能靠自己手动修改css了。

**Comment by salamander-mh** [comment]
已经修改了，从release中复制了样式
