### ISSUE TITLE
easy-mock接口都超时

### ISSUE THREAD

**Issue by airclear** [PanJiaChen/vue-admin-template#191]
easy-mock接口都超时，导致无法预览demo。
建议换一个mock地址

**Comment by PanJiaChen** [comment]
暂时也没找到什么好的替代方案。

**Comment by airclear** [comment]
@PanJiaChen  请问能提供下swagger的文档吗，这样我就可以导到别的工具里了

**Comment by Jesonhu** [comment]
easy-mock 访问有时候特别慢，easy-mock支持在本地开启服务，所以开发的时候可以在本地用 [说明](https://github.com/easy-mock/easy-mock)
