### ISSUE TITLE
有地方设置不同的角色显示不同的菜单吗？

### ISSUE THREAD

**Issue by salamander-mh** [PanJiaChen/vue-admin-template#192]
有些菜单要隐藏

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-admin-template/blob/30cb2df7c88063bb26797b8451c6f725c19c4561/src/views/layout/components/Sidebar/index.vue#L28

可以自己改造。

自己根据权限生成不同的侧边栏数组就可以了。
