### ISSUE TITLE
import path from 'path'

### ISSUE THREAD

**Issue by hwlv** [PanJiaChen/vue-admin-template#200]
path不是node模块吗。怎么在页面上也可以用。

**Comment by PanJiaChen** [comment]
你可以理解为 path也只是一个包，只是巧合它是node提供的。
所以在打包的时候会将它当做一个打包进js。

举个例子

![image](https://user-images.githubusercontent.com/8121621/47075080-57e8c000-d22e-11e8-8645-5bc8a8d215ff.png)
![image](https://user-images.githubusercontent.com/8121621/47075091-5ddea100-d22e-11e8-852f-d934bdc8ef2f.png)
![image](https://user-images.githubusercontent.com/8121621/47075106-646d1880-d22e-11e8-8f39-99b3f76d7b58.png)
