### ISSUE TITLE
项目打包出现这个错误，请问应该怎么修改，谢谢~

### ISSUE THREAD

**Issue by Panpan0403** [PanJiaChen/vue-admin-template#201]
![1539858423 1](https://user-images.githubusercontent.com/20162807/47148906-99e43580-d304-11e8-8e3c-4553ae48b7f4.png)

**Comment by PanJiaChen** [comment]
都没有这个指令。
你查看pagejson.json 中的 script

**Comment by Panpan0403** [comment]
嗯嗯 ，谢谢，但是又出现了这个错误，请问下这个是什么问题，没有思路
![1539860024 1](https://user-images.githubusercontent.com/20162807/47150326-d2860e00-d308-11e8-88b7-7f16e360a92c.png)
 T T

**Comment by Panpan0403** [comment]
嗯嗯，谢谢，运行的时候又出现了这个错误，请问下是什么问题，没有思路  T T


![1539860024 1](https://user-images.githubusercontent.com/20162807/47150360-eb8ebf00-d308-11e8-8bec-55fdd63e0748.png)
