### ISSUE TITLE
npm run build 报错

### ISSUE THREAD

**Issue by airclear** [PanJiaChen/vue-admin-template#208]
![image](https://user-images.githubusercontent.com/4103690/47289134-dd53e200-d62b-11e8-934e-f09329355300.png)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/1222#issuecomment-431992871

你现在只要
删除 node_modules文件夹 和 package-lock.json
然后试试
```bash
npm cache clean --force
npm install --registry=https://registry.npm.taobao.org
```
