### ISSUE TITLE
登录接口，替换线上的，后台返回了token,怎么跳转页面和设置

### ISSUE THREAD

**Issue by konghuan1990** [PanJiaChen/vue-admin-template#219]

**Comment by konghuan1990** [comment]
![image](https://user-images.githubusercontent.com/15864263/48310941-6a0e1200-e5d2-11e8-9414-1bd8cf921593.png)
x

**Comment by chenmychou** [comment]
去掉permission.js就好  还有request.js里拦截code需要更改为你们后端返回的code

**Comment by konghuan1990** [comment]
谢谢，已经解决了
