### ISSUE TITLE
登录页面输入用户名密码，点击Sign in后，Chrome，360浏览器无法跳转；Firefox，IE跳转正常

### ISSUE THREAD

**Issue by szhang6** [PanJiaChen/vue-admin-template#220]
**1.前置条件**：经过配置config\index.js文件的assetsPublicPath: './', npm run build将项目打包后，找到工程目录下的dist目录，打开index.html页面：

**2.现象**：几乎同一时间，在Firefox上登录后，马上登录Chrome，这样试过几次，每次Firefox跳转正常，Chrome无法跳转。

Chrome网络面板请求显示如下（同360浏览器）：
![default](https://user-images.githubusercontent.com/12678848/48323466-4b0d8f80-e667-11e8-9446-8e0875eb405e.png)

Firefox网络面板显示如下（同IE浏览器（版本11））：
![default](https://user-images.githubusercontent.com/12678848/48323490-5f518c80-e667-11e8-9a4f-a02b810f7232.png)

**3.问题**：自己检查，应该是Chrome和360浏览器没有把第二个带token=admin参数的info请求发出去。这个现在还没有找到原因，正在debug。这个是否可以帮忙看一下？有最新进展我也会更新上来。

**4.期望**：在Chrome和360浏览器中，也可以像Firefox一样，正常登陆到dashboard页面。

**Comment by zhangkaicheng521** [comment]
我页遇到这个问题了。Chrome 设置不上cookie。所以，在路由钩子函数那块，getToken 获取不到 token值，就无法跳转页面。

**Comment by zhangkaicheng521** [comment]
打包文件放到服务器运行就ok了

**Comment by PanJiaChen** [comment]
file://协议不支持cookie。
请自己启一个服务来运行。
