### ISSUE TITLE
ie11打开网页，提示"“Promise”未定义"

### ISSUE THREAD

**Issue by myDancer** [PanJiaChen/vue-admin-template#224]
在ie11浏览器下打开https://panjiachen.github.io/vue-admin-template/#/，然后提示如下description"“Promise”未定义"
message"“Promise”未定义"
name"ReferenceError"
number-2146823279
stack"ReferenceError: “Promise”未定义

**Comment by myDancer** [comment]
装了polyfill 就可以了，作者为什么不直接在项目里加上这个呢？而且也没有在文档直接说明ie要使用需要装polyfill 。

**Comment by photonlili** [comment]
Here is the [doc](https://github.com/PanJiaChen/vue-element-admin/wiki#babel-polyfill) from other project, should be working
