### ISSUE TITLE
easy-mock 接口的返回值模板能不能帮忙提供下

### ISSUE THREAD

**Issue by linkwechat** [PanJiaChen/vue-admin-template#232]
由于变更修改代码需要修改参数重新模拟登录过程，实在不想重新mock写一遍全部接口。。。 @PanJiaChen

**Comment by zc910704** [comment]
用postman自己抓一遍啊。。。。

**Comment by zc910704** [comment]
user/login 返回的数据形式为：
‘’‘
{
    "code": 20000,
    "data": {
        "token": "admin"
    }
}
‘’‘
user/info?token=admin返回如下
'''
{
    "code": 20000,
    "data": {
        "name": "name",
        "avatar": "https://wpimg.wallstcn.com/f778738c-e4f8-4870-b634-56703b4acafe.gif",
        "roles": [
            "admin"
        ]
    }
}
'''

**Comment by linkwechat** [comment]
> 用postman自己抓一遍啊。。。。

主要是这个登录参数是有动态判断的，所以提供的模板希望作者最好能给出下，这样就不用每个人都去反推模板了。。。

**Comment by 8pig** [comment]
> > 用邮递员自己抓一遍啊....
> 
> 主要是这个登录参数是有动态判断的，所以提供的模板希望作者最好能给出下，这样就不用每个人都去反推模板了...

f12 NETWORK 不谢

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-admin-template/tree/master/mock

参考 `mock` 下面的文件就可以了。
