### ISSUE TITLE
关于post请求与tinymce上传图片问题

### ISSUE THREAD

**Issue by VonJane** [PanJiaChen/vue-admin-template#238]
您好，以下是我不懂的两个问题，特向您请教。
1.为什么我发送post请求，还会将参数加在url后面呢？
[请求头](http://images.cnblogs.com/cnblogs_com/jianwind/1232489/t_N%7BRA$IMRDEV3ON~Y83DEF8F.png)
如图所见，我用了文章的那个解决方案，发送请求时文章内容过长就会Re
quset header is too large,我想了解为什么我用的post请求还会将参数拼到url后面呢？

2.tinymce编写文章时，右上角有个蓝色上传文件按钮，此按钮上传的文件上传到哪里了呢？我发现它上传后返回的图片地址是data:image/jpeg;base64,开头的，这种地址除了我的机器外，别的机器是否能访问到呢？

**Comment by jingyulong** [comment]
1.发送POST请求，应该是向```https://httpbin.org/post```这个地址请求,这个直接传的是图像二进制数据。可以仔细看下。
2.我只知道上面的，我也正在看后端怎么接收😂

**Comment by VonJane** [comment]
> 1.发送POST请求，应该是向`https://httpbin.org/post`这个地址请求,这个直接传的是图像二进制数据。可以仔细看下。
> 2.我只知道上面的，我也正在看后端怎么接收

还是非常感谢您的不吝赐教。

**Comment by jingyulong** [comment]
@VonJane 你的问题现在弄清楚了吗？可以分享下吗？

**Comment by VonJane** [comment]
> @VonJane 你的问题现在弄清楚了吗？可以分享下吗？

关于后台无法接受的问题，我只是修改了容器的最大请求头容量，但我认为这应该只是缓兵之计，不是最好的办法。

**Comment by VonJane** [comment]
> @VonJane 你的问题现在弄清楚了吗？可以分享下吗？

今天试过了，传了一张79K的图片就不行了，所以还是得另寻他法，不能靠改Tomcat容量。

**Comment by jingyulong** [comment]
@VonJane 可以考虑下分片上传

**Comment by luguokong** [comment]
@VonJane 
1.发送post请求，参数在url中，应该是axios配置错了吧
2.这个项目毕竟是个前端项目，只是模拟文件上传。只是点击了确定后就把文件内容通过提交事件传递到父组件，然后显示出来了。一般实际做法是，在上传成功的回调里，获得后台给的文件存储位置(url)，然后通过提交事件，在富文本组件中显示出来。
