### ISSUE TITLE
v4.0分支 运行npm run dev会报错

### ISSUE THREAD

**Issue by luguokong** [PanJiaChen/vue-admin-template#240]
不配置.postcssrc.js中的autoprefixer，或者不注释掉autoprefixer ，会运行报错

Error: Loading PostCSS Plugin failed: Cannot find module 'autoprefixer'

**Comment by PanJiaChen** [comment]
因为就是依赖autoprefixer的啊。

**Comment by luguokong** [comment]
只是觉得拉下来不能直接跑，体验不好……
