### ISSUE TITLE
build 之后太大，开启gzip后，打包大小没变化 。怎么可以让打的包小一些

### ISSUE THREAD

**Issue by xuyangxy** [PanJiaChen/vue-admin-template#244]
如题，怎么可以让打的包小一点

![image](https://user-images.githubusercontent.com/17880796/50432024-12b9cc00-090a-11e9-9ee4-b8c23173ffa1.png)

![image](https://user-images.githubusercontent.com/17880796/50432072-5d3b4880-090a-11e9-86e7-f874cd1c7ada.png)

**Comment by PanJiaChen** [comment]
首先gzip开了之后肯定会小，没小的话应该是使用不正确。

如果你想让 element-ui变小的话可以使用它的按需加载，具体看其官网。
`chunk-0`目测是 echarts，他也有按需加载。
