### ISSUE TITLE
npm install 报错 /usr/bin/git ls-remote -h -t git://github.com/adobe-webplatform/eve.git  谢谢～

### ISSUE THREAD

**Issue by yuechenxv** [PanJiaChen/vue-admin-template#260]
![image](https://user-images.githubusercontent.com/16622667/51359950-bca10880-1b04-11e9-82df-df057507ee6d.png)

![image](https://user-images.githubusercontent.com/16622667/51359976-d2163280-1b04-11e9-8706-5a6e5b4a755c.png)

**Comment by PanJiaChen** [comment]
用cnpm试试咯

**Comment by yuechenxv** [comment]
![image](https://user-images.githubusercontent.com/16622667/51373051-0c4df700-1b3a-11e9-82cc-26c812350bc5.png)

**Comment by yuechenxv** [comment]
很喜欢你这套模版的样式和功能的，可是。。。

**Comment by PanJiaChen** [comment]
https://blog.csdn.net/baidu_30809315/article/details/86520093

或者用 `cnpm` 试试

**Comment by yuechenxv** [comment]
非常感谢作者的耐心解答，已经正常安装成功
Thanks !

**Comment by Abbyyan** [comment]
多谢作者，可以正常安装成功！
