### ISSUE TITLE
根据后端字段动态导入组件到component,但是import似乎无法找到页面

### ISSUE THREAD

**Issue by vkcyan** [PanJiaChen/vue-admin-template#262]
找到问题了,打扰的大佬了

**Comment by jiaxin666** [comment]
请问是怎么解决的

**Comment by xmut** [comment]
请问是怎么解决的？您回复下，可以省下很多人重复提问

**Comment by xmut** [comment]
自己手痒，将permission.js的“router.addRoutes(accessRoutes)”注释掉。取消注释即可。

// dynamically add accessible routes
router.options.routes = myRoutes // 这句话是我自己添加，用来解决无法动态加载路由的问题
//router.addRoutes(accessRoutes) 这句话被注释掉，导致菜单可以显示，但点击返回空白页

**Comment by xinbingyao** [comment]
> 以下是个人碰到的问题，仅供参考！
> 自己手痒，将permission.js的“router.addRoutes(accessRoutes)”注释掉。取消注释即可。
> 
> // dynamically add accessible routes
> router.options.routes = myRoutes // 这句话是我自己添加，用来解决无法动态加载路由的问题
> //router.addRoutes(accessRoutes) 这句话被注释掉，导致菜单可以显示，但点击返回空白页

myRoutes是哪个？我现在也是这个问题，查看router里的routes没有动态添加上路由，不知道为啥
