### ISSUE TITLE
Error vue-template-admin login

### ISSUE THREAD

**Issue by rtrachelteng** [PanJiaChen/vue-admin-template#263]
Hi!

I just clone one of your templates and realised that there is an error with the login. I have attached a screenshot of the error message (status code 500) and hope you can resolve it on your end. Thanks a lot!
![screenshot 2019-01-19 at 10 03 04 pm](https://user-images.githubusercontent.com/36838392/51427718-04737d00-1c36-11e9-8c91-684e3bff1e2a.png)

**Comment by PanJiaChen** [comment]
easy-mock problem.

https://github.com/PanJiaChen/vue-admin-template/issues/241
