### ISSUE TITLE
浏览器中打印的行数跟IDE中的行数不一致

### ISSUE THREAD

**Issue by Even-Lau** [PanJiaChen/vue-admin-template#270]
Hello,
                                                                                                 
          

例如：在IDE中第88行 console.log( ‘a’ )，浏览器中a的行数却为91

![image](https://user-images.githubusercontent.com/23427420/52099852-de73b280-260f-11e9-8905-89226d31f42b.png)
![image](https://user-images.githubusercontent.com/23427420/52099880-0ebb5100-2610-11e9-8758-f103d0233682.png)

**Comment by PanJiaChen** [comment]
请提供截图。

**Comment by Even-Lau** [comment]
全局查找也只有这么一行



![image](https://user-images.githubusercontent.com/23427420/52028486-2c25e780-254a-11e9-8904-584205c5b8f3.png)

**Comment by PanJiaChen** [comment]
你点进去，看一下源码，对比一下不就知道了。

**Comment by Even-Lau** [comment]
> 你点进去，看一下源码，对比一下不就知道了。



这个具体是什么原因呢，webpack的问题吗？

**Comment by PanJiaChen** [comment]
你都不截图一下。。我知道到底不一样什么？
还有你这3000多行是打包后的代码？

**Comment by Even-Lau** [comment]
> 你都不截图一下。。我知道到底不一样什么？
> 还有你这3000多行是打包后的代码？

hello,

换了个简单点的例子，只有100多行的。代码非打包后的代码

**Comment by PanJiaChen** [comment]
你倒是给我例子啊。。

**Comment by PanJiaChen** [comment]
![image](https://user-images.githubusercontent.com/8121621/52101100-1cbfa080-2615-11e9-92ea-915068430756.png)

你能点进去给我看一下有什么区别么？

请先学会如何提问。太低效了
