### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by rtrachelteng** [PanJiaChen/vue-admin-template#271]
Hi when trying to login there is a network error. Please advice

**Comment by xiaokfc2012** [comment]
same~

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-admin-template/issues/241

**Comment by PanJiaChen** [comment]
https://github.com/easy-mock/easy-mock/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

`easy-mock` problem.
