### ISSUE TITLE
对接后台登录后刷新报 Network Error

### ISSUE THREAD

**Issue by Simplehippo** [PanJiaChen/vue-admin-template#273]
mock项目本地跑没问题的, 对接了后台之后, 登录时也是ok的, 但是在登录后点击刷新页面就会重定向到登录页, 并报错误Network Error.

后台接口已经修改了:
![6cl3pe9 oph3v tr _uk](https://user-images.githubusercontent.com/24547457/52103553-2fd86d80-2621-11e9-9bb2-978fa7c76de5.png)

这是重定向时页面错误:
![b q asdi t u9q9](https://user-images.githubusercontent.com/24547457/52103576-4c74a580-2621-11e9-99e9-4b5ea396b06a.png)

这是chrome控制台(这里为什么还有mock的数据, 还跨域了...):
![r8 s0 eeovvk ph 67i](https://user-images.githubusercontent.com/24547457/52103585-5eeedf00-2621-11e9-9fbf-b960a587c887.png)

看了其他的issue, 注释掉了这一行, 好了...
![zkc 4 umvs0g wym17_i5](https://user-images.githubusercontent.com/24547457/52103630-99587c00-2621-11e9-9d36-e7dfb8acfda0.png)

问题暂时解决....

**Comment by Xanthuim** [comment]
我的也是这个问题，但是注释还是一样的错误
