### ISSUE TITLE
用4.0版本slidebar eslint一直报eslint-disable vue/require-component-is这个错误，我在rule off掉依旧vscode在报错

### ISSUE THREAD

**Issue by chenweibo** [PanJiaChen/vue-admin-template#274]
在.eslintrc.js 
<img width="804" alt="2019-02-02 10 53 26" src="https://user-images.githubusercontent.com/19586007/52165556-60152e80-273d-11e9-957d-6b3f86df606b.png">  也无效啊 很烦 虽然页面不报错

**Comment by chenweibo** [comment]
yarn 安装的

**Comment by PanJiaChen** [comment]
这个没什么问题，只是一个vscode插件的抛的错，不会对开产生什么问题。

**Comment by webpdr** [comment]
> 这个没什么问题，只是一个vscode插件的抛的错，不会对开产生什么问题。

这个用法我google查了，还是没搞明白，求大神指导，谢谢

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/1700

我暂时行改了下写法，兼容这个warning。

**Comment by chenweibo** [comment]
这个问题已经解决了官方给了一个配置项关闭了这个问题

**Comment by PanJiaChen** [comment]
不靠谱，为了找一个问题，把所有校验都关了，本末倒置了吧。

**Comment by larssonsun** [comment]
大佬你好，我发现这个文件你又改回去了？而且位置也移动到src/layout下面了？
