### ISSUE TITLE
大佬能把4.0的基础模板cli 升级到3.3吗 现在还是默认3.0的。发现有些配置项已经弃用了。

### ISSUE THREAD

**Issue by chenweibo** [PanJiaChen/vue-admin-template#275]
baseUrl
从 Vue CLI 3.3 起已弃用，请使用publicPath。

# publicPath
Type: string

Default: '/'

部署应用包时的基本 URL。用法和 webpack 本身的 output.publicPath 一致，但是 Vue CLI 在一些其他地方也需要用到这个值，所以请始终使用 publicPath 而不要直接修改 webpack 的 output.publicPath。

默认情况下，Vue CLI 会假设你的应用是被部署在一个域名的根路径上，例如 https://www.my-app.com/。如果应用被部署在一个子路径上，你就需要用这个选项指定这个子路径。例如，如果你的应用被部署在 https://www.my-app.com/my-app/，则设置 publicPath 为 /my-app/。

这个值也可以被设置为空字符串 ('') 或是相对路径 ('./')，这样所有的资源都会被链接为相对路径，这样打出来的包可以被部署在任意路径，也可以用在类似 Cordova hybrid 应用的文件系统中。

之前这个配置项好像有个在特定情况下有BUG 所以好像弃用了。 

什么时候用空能把包里面的插件改成3.3版本的 我怕自己改可能改出BUG了。

**Comment by PanJiaChen** [comment]
4.0之路任重而道远。

再发布一个版本之后，我会集中开发4.0，争取早日发布吧。

**Comment by mymx2** [comment]
> 4.0之路任重而道远。
> 
> 再发布一个版本之后，我会集中开发4.0，争取早日发布吧。

加油

**Comment by zhychao** [comment]
这个vue-element-admin 和vue-admin-template差别很大了吗

**Comment by PanJiaChen** [comment]
优先会升级`vue-element-admin`

**Comment by chenweibo** [comment]
我一直在关注4.0 所以我是直接用vue-element-admin 4.0分支的作为模板修改开发了。我之前也是看这个模板进度没上面的快。

**Comment by PanJiaChen** [comment]
已更新。
