### ISSUE TITLE
关于使用el-table的template的更新数据出现的问题

### ISSUE THREAD

**Issue by hwgq2005** [PanJiaChen/vue-admin-template#280]
![image](https://user-images.githubusercontent.com/5905904/53009856-66164980-3477-11e9-8e2d-32799ced223b.png)

![image](https://user-images.githubusercontent.com/5905904/53009935-8f36da00-3477-11e9-90c7-5ace3690ee1c.png)

**Comment by dongsuo** [comment]
把 Vue 版本换成2.5.2试一下？

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/1628
