### ISSUE TITLE
二级路由只有一个，三级路由全都为hidden时 报错

### ISSUE THREAD

**Issue by zwtgit** [PanJiaChen/vue-admin-template#282]
![image](https://user-images.githubusercontent.com/22927679/53074843-bdbfbe00-3526-11e9-9055-0ad383e9b66b.png)
报错条件：
![image](https://user-images.githubusercontent.com/22927679/53075013-260e9f80-3527-11e9-9acf-eac89e9d85e3.png)

**Comment by PanJiaChen** [comment]
按照你的配置没能重现错误。

请确定一下使用的是否是最新代码。
提供一下电脑版本： Mac|| windows
浏览器是什么？

**Comment by zwtgit** [comment]
windows 10      
permission-control版本

**Comment by PanJiaChen** [comment]
真不能重现，你更新一下代码试试？

**Comment by zwtgit** [comment]
我重新拉的代码，果然没问题了，可能是我改的地方出了问题，十分感谢
