### ISSUE TITLE
easy-mock上接口问题

### ISSUE THREAD

**Issue by useryechen** [PanJiaChen/vue-admin-template#284]
作者您好，首先非常感谢您开放项目，可以让我直接进行项目开发，避免基础框架搭建。能否将easy-mock上的接口开放出来看看，因为easy-mock现在的访问人数越来越多，导致服务器响应特别慢，我已经将超时时间改了，但是经常还是会没有响应，所以想自己用node写，不然太影响开发效率了。通过抓包也得到了一些接口，但是不知道有没有做一些校验，目前我用node没有做任何校验，不知道后台返回的数据有什么生成规则，麻烦能否将接口的参数做一说明，万分感谢

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-admin-template/pull/281

现在线上版本可以使用 本地mock了。
数据格式的话参照 `https://github.com/PanJiaChen/vue-admin-template/tree/master/mock`就可以了。

**Comment by useryechen** [comment]
> #281
> 
> 现在线上版本可以使用 本地mock了。
> 数据格式的话参照 `https://github.com/PanJiaChen/vue-admin-template/tree/master/mock`就可以了。

多谢回复，中午那会儿找到本地的mock数据了
