### ISSUE TITLE
v-bind不带属性绑定方法

### ISSUE THREAD

**Issue by webpdr** [PanJiaChen/vue-admin-template#285]
在views/layout/components/Sidebar/Link.vue组件
![_20190225114826](https://user-images.githubusercontent.com/22935525/53313257-7f921800-38f3-11e9-9d34-84266a1a65bf.png)

如果按照提示修改：
v-bind:is="linkProps(to)"
那么siderbar页面会丢失侧边栏内容。
下图为修改后，丢失部分内容的siderbar
![image](https://user-images.githubusercontent.com/22935525/53313369-0d6e0300-38f4-11e9-9f48-04578cb55e61.png)

正常的siderbar
![image](https://user-images.githubusercontent.com/22935525/53313464-6c337c80-38f4-11e9-9dd1-6b2ed6d2aa89.png)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-admin-template/issues/274
