### ISSUE TITLE
$route.matched获取的路由记录，使用filter时，容易出错

### ISSUE THREAD

**Issue by webpdr** [PanJiaChen/vue-admin-template#286]
在src/components/Breadcrumb/index.vue组件中
第38行：
this.levelList = matched.filter(item => item.meta && item.meta.title && item.meta.breadcrumb !== false)

其中item.meta.breadcrumb 即最后一个判断条件，如果将其更改为item.meta.anyname都会判断为真
将38行更改为
this.levelList = matched.filter(item => item.meta && item.meta.title && false !== false)
则判断为假

**Comment by PanJiaChen** [comment]
没懂你要表达什么？

**Comment by webpdr** [comment]
> 没懂你要表达什么？
> 
> `breadcrumb !== false`为什么改成`false !== false`

我当时的想法是：meta中没有发现breadcrumb
既然没有breadcrumb，那么leveList便不会被赋值，结果是leveList被赋值了
后面尝试发现最后一个判断条件item.meta.keyName中的keyName无论为何值，整个语句都判断为真

**Comment by PanJiaChen** [comment]
但`breadcrumb`是一个options啊。。。文档里有写吧。
https://github.com/PanJiaChen/vue-admin-template/blob/7725f72bebc51db48f444e22f71572d3e9ed7ee0/src/router/index.js#L22

**Comment by webpdr** [comment]
> 文档里有写吧。

现在我的问题是：先不管meta中的breadcrumb
下面2行代码
this.levelList = matched.filter(item => item.meta && item.meta.title && item.meta.**anyKeyName** !== false)
this.levelList = matched.filter(item => item.meta && item.meta.title && item.meta.**breadcrumb** !== false)
运行结果是一样的

**Comment by PanJiaChen** [comment]
有什么问题么？

```js
const a=undefined //true
const b=false //false
const c=true //true
const d='d' //true

```

**Comment by webpdr** [comment]
> 有什么问题么？
> 
> ```js
> const a=undefined //true
> const b=false //false
> const c=true //true
> const d='d' //true
> ```

懂了，谢谢
