### ISSUE TITLE
打包后，页面报Refused to apply style from '<URL>' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

### ISSUE THREAD

**Issue by chengxianyi** [PanJiaChen/vue-admin-template#287]
具体报错信息：

Refused to apply style from '<URL>' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
index.html?_ijt=6is8mpcu5r7aoeulkfq4d3qbv:1 Refused to apply style from 'http://localhost:63342/static/css/chunk-elementUI.8441406c.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by PanJiaChen** [comment]
随手一查就有相关问题。

**Comment by chengxianyi** [comment]
对不起，打扰了，是我基础不够扎实，没有深入研究过webnpack，使用了默认的打包路径
