### ISSUE TITLE
npm run dev页面空白

### ISSUE THREAD

**Issue by webpdr** [PanJiaChen/vue-admin-template#288]
问题：npm run dev之后，页面空白
tag标签有图标
![image](https://user-images.githubusercontent.com/22935525/53428132-317d3180-3a25-11e9-86da-b3877e6987cf.png)

打开dist/index.html有页面内容，只是无法登陆

**Comment by PanJiaChen** [comment]
请用正确的姿势提问。

**Comment by webpdr** [comment]
> 请用正确的姿势提问。
> 
> 至少你要提供命令行是否报错，浏览器是否报错这些信息吧。不然让人家怎么帮助你。

抱歉，回复晚了。
看了你的回复后我根据浏览器报错修正了程序，现在可以正常运行了，谢谢！
