### ISSUE TITLE
vue-admin-template无法兼容ie浏览器

### ISSUE THREAD

**Issue by swxin** [PanJiaChen/vue-admin-template#290]
在 vue-element-admin项目中是使用babel-polyfill可以兼容IE浏览器
同样的方法，在vue-admin-template项目中无法兼容

**Comment by swxin** [comment]
查看了一下编译后的js文件，里面还是有es6的语法，箭头函数 ,const ,let等

**Comment by PanJiaChen** [comment]
是你没配对吧。。

**Comment by PanJiaChen** [comment]
兼容方法文档写的很清楚了。两个项目本身添加polyfill没有什么区别。

**Comment by PiersPc** [comment]
我也遇到这个问题了，编译后还是有const 然后ie报语法错误

**Comment by swxin** [comment]
大概原因我知道了，编译的时候src的目录没有用到babel转换
但我不知道怎么正确地改
 我的改法
{ test: /\.js$/, exclude: /node_modules/, loader: "babel-loader" }
再加上 babel-polyfill

**Comment by PiersPc** [comment]
把根目录mock 文件夹放在src目录，再把main.js引入mock的路径改一下就可以了

**Comment by PanJiaChen** [comment]
Fixed in https://github.com/PanJiaChen/vue-admin-template/commit/6716ddb0d4e6fe650c774d9ff996cc7e7d77ba02

**Comment by dongshihao666** [comment]
这个问题大家有解决的吗
