### ISSUE TITLE
编译结果好肥

### ISSUE THREAD

**Issue by hiobama** [PanJiaChen/vue-admin-template#294]
[按需引入](https://element.eleme.io/#/zh-CN/component/quickstart#an-xu-yin-ru) 好像也很大，这是ele的所有组件都要用到吗？

**Comment by hiobama** [comment]
改成按需引入之后，Entrypoints 由 970K 减小到 747K

**Comment by PanJiaChen** [comment]
所以和本项目有什么关系？这是你自己的决策问题。

**Comment by hiobama** [comment]
问题是文件有点大，747K 还是远远超出 webpack 建议的 244K，有没有优化的可能？

**Comment by PanJiaChen** [comment]
https://bundlephobia.com/result?p=element-ui@2.6.1

GZIP 之后还行吧。

**Comment by hiobama** [comment]
升级到 element-ui@2.6.1 又减小几十 K，目测升级之后没有BUG，至少在 vue-admin-template 里面没法问题。
