### ISSUE TITLE
 Unknown custom element: <svg-icon> 有人遇到类似问题吗，死活找不到哪里出错了

### ISSUE THREAD

**Issue by supersea** [PanJiaChen/vue-admin-template#297]
![image](https://user-images.githubusercontent.com/5726976/54030425-86b80080-41e6-11e9-8a0d-a2d688e6be22.png)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-admin-template/blob/1a6ae849df754c6608f83e8d2ef879988714c79a/src/icons/index.js#L5

需求全局注册。
