### ISSUE TITLE
vue-admin-template 跟 vue-element-admin 脱节了，vue-element-admin 无法 build 成功！！！！

### ISSUE THREAD

**Issue by toruksmakto** [PanJiaChen/vue-admin-template#298]
两份代码稍微有点不一致就得出小问题，就得找半天，你们说怎么复制粘贴怎么搞？？？好好的项目要废了啊

**Comment by hiobama** [comment]
为了更好维护，建议是在 vue-element-admin 底下建一个 vue-admin-template 分支，而不是以独立仓库形式存在。。。。。git merge merge merge merge

**Comment by PanJiaChen** [comment]
分两个项目会对对造成什么影响么？

暂时当做一个分支其实也不是很好维护。

**Comment by hiobama** [comment]
分两个项目应该就用不了 git merge 了吧，只能手动合并代码。反正我现在直接用 vue-element-admin 开发了。

**Comment by hiobama** [comment]
文档里说，需要什么功能就复制粘贴，可是复制过去出现一些错误很难解决，因为两份代码之间差别越来越大，脱节了，可能你也顾不了那么多。使用 git merge 可以保证代码的继承关系，强制两份代码之间保持同步。

**Comment by PanJiaChen** [comment]
其实不好做，其实现在最大的区别是国际化。之后 `vue-element-admin`会去国际化，所以会好一点。

现在我大部分精力在搞 `v4.0`版本，上线之后我来考虑一下，怎么解决这个问题吧

**Comment by PanJiaChen** [comment]
已更新。
