### ISSUE TITLE
侧边栏折叠后，鼠标移上去不能显示三级菜单

### ISSUE THREAD

**Issue by duanmw** [PanJiaChen/vue-admin-template#300]
我clone下来，运行发现侧边栏折叠后，鼠标移上去不能显示三级菜单，自己又添加了几个，同样3级菜单及以后的都不能显示，试了线上demo是没问题的，不知道怎么回事

![2019-03-12_205512](https://user-images.githubusercontent.com/31787613/54201946-e3c6f580-4509-11e9-8b75-9ce84a1cd92e.png)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-admin-template/commit/1a6ae849df754c6608f83e8d2ef879988714c79a

你确定一下是最新的代码么？你的这个bug，几天前已经修复了。

**Comment by duanmw** [comment]
> [1a6ae84](https://github.com/PanJiaChen/vue-admin-template/commit/1a6ae849df754c6608f83e8d2ef879988714c79a)
> 
> 你确定一下是最新的代码么？你的这个bug，几天前已经修复了。

呃，我之前用的permission分支，刚刚重新试了下master,没问题了
