### ISSUE TITLE
使用vue-admin-template过程中，配置了proxyTable后，跨域存在问题！

### ISSUE THREAD

**Issue by qiaoYan318** [PanJiaChen/vue-admin-template#304]
配置好了proxyTable后，采用现在已经封装好的request.js发送请求，会产生跨域问题，报错
Access to XMLHttpRequest at 'http://192.168.251.100/api/zzz/public/admin/login/index' from origin 'http://127.0.0.1:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

但是我直接采用axios.post提交请求的话，就没有问题，请求成功。
 const username = this.loginForm.username
          const password = this.loginForm.password
          this.$axios.post('/api/zzz/public/admin/login/index', {
            username, password
          }).then(resp => {
            const data = resp.data
            const msg = data.msg

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-admin-template/blob/4bbdf5ee0e92e910f266a78d8fb3a8b882e9c0c5/src/utils/request.js#L8

`request.js`分装了 base_url。所以应该是你的 `proxy`写的不对，没有匹配路由。

**Comment by qiaoYan318** [comment]
你好，我还是这里没搞懂，这里的baseUrl是在本地环境和线上环境里面配置的url吗？那这样我proxy里面应该怎么匹配路由呢？我现在把Dev和prod里面的BASE_API: '"http://192.168.251.100/zzz/public/admin"',设置成这样了。proxy里面target: process.env.BASE_API,设置成这样，去掉了mock，还是报跨域的错误。

**Comment by qiaoYan318** [comment]
> [vue-admin-template/src/utils/request.js](https://github.com/PanJiaChen/vue-admin-template/blob/4bbdf5ee0e92e910f266a78d8fb3a8b882e9c0c5/src/utils/request.js#L8)
> 
> Line 8 in [4bbdf5e](/PanJiaChen/vue-admin-template/commit/4bbdf5ee0e92e910f266a78d8fb3a8b882e9c0c5)
> 
>  baseURL: process.env.BASE_API, // api 的 base_url 
> `request.js`分装了 base_url。所以应该是你的 `proxy`写的不对，没有匹配路由。
> 实际请求地址是 `base_url+/api/xxx/`
你好，我还是这里没搞懂，这里的baseUrl是在本地环境和线上环境里面配置的url吗？那这样我proxy里面应该怎么匹配路由呢？我现在把Dev和prod里面的BASE_API: '"http://192.168.251.100/zzz/public/admin"',设置成这样了。proxy里面target: process.env.BASE_API,设置成这样，去掉了mock，还是报跨域的错误。

**Comment by qiaoYan318** [comment]
> [vue-admin-template/src/utils/request.js](https://github.com/PanJiaChen/vue-admin-template/blob/4bbdf5ee0e92e910f266a78d8fb3a8b882e9c0c5/src/utils/request.js#L8)
> 
> Line 8 in [4bbdf5e](/PanJiaChen/vue-admin-template/commit/4bbdf5ee0e92e910f266a78d8fb3a8b882e9c0c5)
> 
>  baseURL: process.env.BASE_API, // api 的 base_url 
> `request.js`分装了 base_url。所以应该是你的 `proxy`写的不对，没有匹配路由。
> 实际请求地址是 `base_url+/api/xxx/`

    proxyTable: {
      '/api': {
        target: process.env.BASE_API,
        changeOrigin: true,
        pathRewrite: {
          '^/api': '/'
        }
      }
    },这是我的proxy配置

**Comment by PanJiaChen** [comment]
请自己自行查看`proxyTable`文档和或者自己检索相关文章
