### ISSUE TITLE
登录界面显示密码功能工作不正常

### ISSUE THREAD

**Issue by yuzifu** [PanJiaChen/vue-admin-template#310]
第一次打开登录界面，密码框显示小黑点，启用显示密码功能后，密码框显示的是placeholder值，关闭显示密码功能后，密码框显示的依然是placeholder值。
我把密码框组件的placeholder属性删除了，启用显示密码之后，密码框显示为空，关闭显示密码功能，密码框依然显示为空。

这个问题在vue-element-admin项目不存在，我对比了这两个项目的login界面源码，它们的实现方式是一样的。

我查看了Element文档，el-input组件实现显示密码功能，只需要增加show-password即可，但vue-admin-template的实现方式却不一样，这是为何？是为了定制显示密码图标的样式吗？

**Comment by PanJiaChen** [comment]
第一个问题，没看懂你想表达什么

第二个问题，`show-password`是element 之前不久才加上的，而且本身也没有需要用的意义。input type 就够用了。

**Comment by yuzifu** [comment]
> 第一个问题，没看懂你想表达什么

显示密码功能工作正常的话，应该是：
1，密码框有值时，默认显示为小圆点，单击显示密码图标，密码框显示真实值，再次单击显示密码图票，密码框显示为小圆点。
2，密码框无值时，显示placeholder

**Comment by yuzifu** [comment]
我把项目改成了CDN方式引用elementui，并且没有指定版本，加载的是最新的elementui 2.6.5版本，项目指定的版本则是2.4.6。
修复方法：通过CDN方式引用elementui时指定与项目一致的版本。
