### ISSUE TITLE
您好，请问下你线上的预览的这个是怎么打包的，我也想把模拟数据打包进去

### ISSUE THREAD

**Issue by Heendy** [PanJiaChen/vue-admin-template#311]
在打包的时候我也想把mock 的数据打包进去 因为我们这边的接口还没有开发完成但是又想看效果，所以想把mock 的数据一起打包进去 然后build 发布到网络上。可是我打包了好多次都没打包成功，打包成功之后点击登录 没有反应。

**Comment by PanJiaChen** [comment]
你是本地预览的把，需要自己本地启一个服务

**Comment by Heendy** [comment]
自己的服务器？是打包完之后把dist的文件夹挂上的那种服务器么？

**Comment by PanJiaChen** [comment]
本地启一个服务。 如 [serve](https://github.com/zeit/serve) 这种库。

**Comment by Heendy** [comment]
抱歉，我没明白你的意思，如果服务器的话  我这边是用iis 的，但是这个和打包完之后的有什么关联么？我是想把我的mock 数据 和项目文件一起打包发布到网上 不止给本地的人预览 还要能给线上的人预览的那种。

**Comment by Heendy** [comment]
您的意思是把mock数据在本地部署一个服务器？

**Comment by PanJiaChen** [comment]
你回答了你本地登录不了的原因，如果是 localhost的文件不能访问cookie，所以登录不了。

mock的文档，文档写的很清楚了。 可以使用mockjs 纯前端mock 不需要任何后端服务。或者用easy-mock或者自己架一个mock服务。

请先自己看文档。

**Comment by Heendy** [comment]
我的所有mock数据都是本地的mock.js 创建出来的，那如果不是mock 数据的问题  那就是因为localhost 的文件访问不了cookie 所以登录不了 的原因咯？那我需要 或者应该怎么修改呢？ 谢谢您！

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/1030

**Comment by Heendy** [comment]
谢谢 谢谢 谢谢！万分感谢！感谢您花时间回答了我的问题！
