### ISSUE TITLE
Custom breadcrumbs

### ISSUE THREAD

**Issue by magengxin** [PanJiaChen/vue-admin-template#317]
How to set breadcrumbs to achieve inconsistency between the title of left button and breadcrumbs

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-admin-template/blob/master/src/components/Breadcrumb/index.vue

Besides, what effect do you want?

**Comment by magengxin** [comment]
![需求](https://user-images.githubusercontent.com/23067574/55394656-60317f00-5572-11e9-9db0-9eaa6a7ad22e.png)
公司要实现这个效果

**Comment by PanJiaChen** [comment]
自己改改代码就好了吧。。

**Comment by magengxin** [comment]
已经改了
但是它们是一个变量
修改了还是一起变了

**Comment by PanJiaChen** [comment]
变量指什么？

**Comment by magengxin** [comment]
![image](https://user-images.githubusercontent.com/23067574/55454199-89551c80-5611-11e9-9af0-7500ce4d5bcb.png)

**Comment by magengxin** [comment]
if(first && first.path == '/recommend/index'){
        // first.meta.title = '1121'
      }

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/1818
