### ISSUE TITLE
动态权限和动态侧边栏

### ISSUE THREAD

**Issue by iiiiiitboy** [PanJiaChen/vue-admin-template#318]
因为我是个Java开发者，对前端技术不太熟悉。我在基础模板的/src/router/index.js中添加了export const asyncRouterMap = []并在其中添加了路由信息，但是无效果，请问还需要添加什么代码，感谢指教一下，谢谢！
```
export const asyncRouterMap = [
  {
    path: '/test',
    component: Layout,
    redirect: '/test/index',
    name: 'Test',
    meta: {
      title: '测试'
    },
    children: [
      {
        path: 'index',
        component: () => import('@/views/test/index/index'),
        name: 'TestIndex',
        meta: { title: '测试' }
      }
    ]
  },

  { path: '*', redirect: '/404', hidden: true }
]
```

**Comment by PanJiaChen** [comment]
什么叫无效果

**Comment by iiiiiitboy** [comment]
就是侧边栏看不到
![image](https://user-images.githubusercontent.com/20620562/55455951-3c287900-5618-11e9-938a-124cef65dc04.png)

**Comment by iiiiiitboy** [comment]
> 什么叫无效果

就是侧边栏看不到
![image](https://user-images.githubusercontent.com/20620562/55455987-5a8e7480-5618-11e9-80e8-95ff28e77e3e.png)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-admin-template/blob/permission-control/src/router/index.js

这个分支才支持动态权限。

不需要动态权限的路由写在 `constantRouterMap`中。

**Comment by iiiiiitboy** [comment]
好的，感谢！
