### ISSUE TITLE
动态增加导航栏，能得到匹配的数据但是导航栏不显示

### ISSUE THREAD

**Issue by y5134828** [PanJiaChen/vue-admin-template#319]
![微信图片_20190403152618](https://user-images.githubusercontent.com/30194048/55460679-23729000-5625-11e9-9823-376aac6ca58c.png)

在登录时getInfo可以判断得到对应的权限，进入首页左侧导航栏没有动态加载数据

**Comment by y5134828** [comment]
已解决  需要在 slidebar/index.vue 中修改循环的变量  为vuex中修改的变量  
参考:
![微信图片_20190403171904](https://user-images.githubusercontent.com/30194048/55467807-a0593600-5634-11e9-9677-2c7b5452630a.png)

**Comment by WalkerKing** [comment]
多谢大佬分享，借助您的经验，解决我的问题。
