### ISSUE TITLE
4.0版本点击登录Login方法异常

### ISSUE THREAD

**Issue by liucien** [PanJiaChen/vue-admin-template#329]
![image](https://user-images.githubusercontent.com/32785166/56022949-60ced000-5d3f-11e9-86f4-d429188dd247.png)

刚开始以为是这两个方法没对应，但是修改后依旧没用~~！
![image](https://user-images.githubusercontent.com/32785166/56023080-b5724b00-5d3f-11e9-964b-991304204718.png)

![image](https://user-images.githubusercontent.com/32785166/56023096-be631c80-5d3f-11e9-9d60-747f937abcee.png)

**Comment by PanJiaChen** [comment]
你这明显不是线上代码。

**Comment by liucien** [comment]
![image](https://user-images.githubusercontent.com/32785166/56023708-12bacc00-5d41-11e9-95eb-d27813e43ba3.png)
![image](https://user-images.githubusercontent.com/32785166/56023723-1f3f2480-5d41-11e9-8009-3f4975120140.png)
是4.0版本的代码，我刚clone下来的，难不成4.0还不能用么 /捂脸

**Comment by PanJiaChen** [comment]
不好意思，看混项目了。
本项目`4.0`还不能用。下周会发布正式版本。

**Comment by liucien** [comment]
好的，期待大佬下周发布

**Comment by MoonCheung** [comment]
我本来想将这个后台管理源代码里面mock修改成自己本地koa2服务器:http//127.0.0.1:3030/api/login，然后在login页面点击login按钮出现报错，差不多类似楼主上面代码在控制台提示错误的，怎么解决？
![image](https://user-images.githubusercontent.com/19801190/57176003-5eb2e980-6e85-11e9-8427-1b7e4a969aea.png)
![image](https://user-images.githubusercontent.com/19801190/57176018-7b4f2180-6e85-11e9-9719-8adc687bec8f.png)
![image](https://user-images.githubusercontent.com/19801190/57176030-8a35d400-6e85-11e9-9eb1-9c39633e3736.png)
