### ISSUE TITLE
正式版4.0 登录报错 Cannot POST /mock/user/login

### ISSUE THREAD

**Issue by Ale-cc** [PanJiaChen/vue-admin-template#335]
刚刚更新到正式版的登录用不上， 一时没找到问题所在。
`Cannot POST /mock/user/login`
截图如下：
![WX20190422-112321](https://user-images.githubusercontent.com/18302674/56481387-522baa00-64f1-11e9-8b76-72efffeafa03.png)
<img width="678" alt="WX20190422-112119@2x" src="https://user-images.githubusercontent.com/18302674/56481389-5657c780-64f1-11e9-9a3e-5d29ad4687d9.png">

关键是找不到/dev-api对应的地方，而且好像请求的mock目录也不对吧？

**Comment by PanJiaChen** [comment]
mock js 只会mock本地服务。
线上服务请切换自己的api地址。
或者开启这段代码。

https://github.com/PanJiaChen/vue-admin-template/blob/5dd62efed1f7838c4351a3850d932316988782dc/src/main.js#L23-L24
