### ISSUE TITLE
state.roles的数据格式问题

### ISSUE THREAD

**Issue by lostapple2017** [PanJiaChen/vue-admin-template#337]
用了自己的服务器后台，登录后返回的roles只能是字符串格式（'admin,editor'这样），于是在store的user.js里修改提交roles语句为commit('SET_ROLES', data.roles.split(','))，在页面部分可以观察到取state.roles确实是数组。但是很奇怪的，在permission.js里，传递进来的roles参数却仍然是字符串（'admin,editor'这样）而不是数组，所以路由检查权限时还是的改成：accessedRoutes = filterAsyncRoutes(asyncRoutes, roles.split(','))。
疑问的是：命名提交到state里的roles已经是数组了，为什么permission.js里取到的roles参数仍然是字符串？

**Comment by PanJiaChen** [comment]
请自己debug

**Comment by lostapple2017** [comment]
我跟踪了呀：
user.js里：
  SET_ROLES: (state, roles) => {
    state.roles = roles
    console.log('after set:')
    console.log(state.roles)
  }
permission.js里：
const actions = {
  generateRoutes({ commit }, roles) {
    return new Promise(resolve => {
      console.log('enter action:')
      console.log(roles)
      let accessedRoutes
      if (roles.includes('admin')) {
        accessedRoutes = asyncRoutes || []
      } else {
        accessedRoutes = filterAsyncRoutes(asyncRoutes, roles.split(','))
      }
      commit('SET_ROUTES', accessedRoutes)
      resolve(accessedRoutes)
    })
  }
}
输入是下面这样的，不知道中间漏了什么环节：
![image](https://user-images.githubusercontent.com/25719947/56487717-bf9a0380-650e-11e9-82d3-bf866abea5eb.png)

**Comment by lostapple2017** [comment]
不好意思找到了，在/permission里发现，原来/store/modules/permission.js的roles不是从状态里取的。
          const { roles } = await store.dispatch('user/getInfo')
          // generate accessible routes map based on roles
          const accessRoutes = await store.dispatch('permission/generateRoutes', roles)
