### ISSUE TITLE
基础版release4.1问题

### ISSUE THREAD

**Issue by luoxulx** [PanJiaChen/vue-admin-template#338]
版本：新下载的 release4.1
说明：只修改了一个登录背景图，普通登录成功后问题如下
![image](https://user-images.githubusercontent.com/35016570/56492623-f7a94280-651e-11e9-821a-a46e7d0d8b91.png)
望大佬指点一二

**Comment by luoxulx** [comment]
> 版本：新下载的 release4.1
> 说明：只修改了一个登录背景图，普通登录成功后问题如下
> ![image](https://user-images.githubusercontent.com/35016570/56492623-f7a94280-651e-11e9-821a-a46e7d0d8b91.png)
> 望大佬指点一二

自已的问题。。。

**Comment by lostapple2017** [comment]
我估计你这个跟我碰到的是差不多问题。你后台返回的roles是什么数据格式？如果不是数组（比如字符串），就会出现这样的错误。
我的情况是，后台roles返回的是字符串格式比如‘admin,editor’，这样的话你需要在/store/modules/user.js和/permission.js两个文件里对roles进行处理（加个.split(',')就可以转成数组了）。

**Comment by luoxulx** [comment]
> 我估计你这个跟我碰到的是差不多问题。你后台返回的roles是什么数据格式？如果不是数组（比如字符串），就会出现这样的错误。
> 我的情况是，后台roles返回的是字符串格式比如‘admin,editor’，这样的话你需要在/store/modules/user.js和/permission.js两个文件里对roles进行处理（加个.split(',')就可以转成数组了）。

返回的response少写了一层data
