### ISSUE TITLE
vue-admin-template 基础模板可以添加tagsview模块吗 

### ISSUE THREAD

**Issue by yoZerY** [PanJiaChen/vue-admin-template#344]

**Comment by PanJiaChen** [comment]
目前默认不会添加这个功能。需要手动复制相关代码。

**Comment by yoZerY** [comment]
复制容易出问题   这个功能挺常用的 😄

**Comment by mcc-like-thinking** [comment]
> 目前默认不会添加这个功能。需要手动复制相关代码。

你好，我复制了tagsview源码，但是当打开多可页面时，tagsview没有横向滚动条，你有遇到这个问题吗？

**Comment by jee4a** [comment]
增加tagsView功能步骤：

1，从vue-element-admin复制文件：
vue-admin-template\srclayout\components\TagsView.vue
vue-admin-template\srcstore\modules\tagsView.js
vue-admin-template\src\components\ScrollPane 文件夹
vue-admin-template\static 文件夹
vue-admin-template\src\lang 文件夹
vue-admin-template\src\utils\i18n.js


2，修改 vue-admin-template\src\layout\components\AppMain.vueAppMain.vue文件，新增以下内容：
 
```
<template>
  <section class="app-main">
    <transition name="fade-transform" mode="out-in">
      <router-view :key="key" />
      <keep-alive :include="cachedViews">
        <router-view></router-view>
      </keep-alive>
    </transition>
  </section>
</template>
```
```
export default {
  name: 'AppMain',
  computed: {
    cachedViews() {
      return this.$store.state.tagsView.cachedViews
    },
    key() {
      return this.$route.path
    }
  }
}
```

3 ，修改vue-admin-template\src\layout\components\index.js，新增如下行：
`export { default as TagsView } from './TagsView'`

4，vue-admin-template\src\layout\index.vue
```
<template>
  <div :class="classObj" class="app-wrapper">
    <div v-if="device==='mobile'&&sidebar.opened" class="drawer-bg" @click="handleClickOutside" />
    <sidebar class="sidebar-container" />
    <div class="main-container">
      <div :class="{'fixed-header':fixedHeader}">
        <navbar />
      </div>
      <tags-view />
      <app-main />
    </div>
  </div>
</template>
```
`import { Navbar, Sidebar, AppMain, TagsView } from './components'`
 
```
components: {
    Navbar,
    Sidebar,
    AppMain,
    TagsView
  },
```

5，修改  vue-admin-template\src\store\getters.js，增加：
```
visitedViews: state => state.tagsView.visitedViews,
cachedViews: state => state.tagsView.cachedViews,
```
6，修改  vue-admin-template\src\store\index.js 
`import tagsView from './modules/tagsView'`
```
const store = new Vuex.Store({
  modules: {
    app,
    permission,
    settings,
    tagsView,
    user
  },
  getters
})
```
7,修改  vue-admin-template\src\main.js
`import i18n from './lang' // Internationalization`

```
new Vue({
  el: '#app',
  router,
  store,
  i18n,
  render: h => h(App)
})

```

**Comment by LLDLZ** [comment]
@jee4a  ts版也是这样改吗
