### ISSUE TITLE
用了你的tempalte 想问下作者的tinymce组件为什么值会固化

### ISSUE THREAD

**Issue by jamesbake** [PanJiaChen/vue-admin-template#346]
出现在 <tinymce v-model="xx"/>
xx = ""空值后  就会有bug

**Comment by jamesbake** [comment]
tinymce v-model="xx"

**Comment by jamesbake** [comment]
对xx再次赋值就不是正确的值了,项目有点急 ,作者能回复下么

**Comment by jamesbake** [comment]
Tinymce  index.vue中添加了以下就解决了 
 watch: {
    value(val, oldval) {
     
      if ((!this.hasChange && this.hasInit) || val != oldval) {
        this.$nextTick(() =>
          window.tinymce.get(this.tinymceId).setContent(val || ''))
      }
    },

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/zh/feature/component/rich-editor.html#tinymce

https://github.com/PanJiaChen/vue-element-admin/issues/1365

**Comment by jamesbake** [comment]
多谢
