### ISSUE TITLE
【建议】提供一个带有tagsview的版本

### ISSUE THREAD

**Issue by Eter365** [PanJiaChen/vue-admin-template#349]
> #131
> #272
> #325
> #344 
整理了一下issue列表，关于tagsview的问题比较多， 
有如下建议：
1. 可以提供一个带有tagsview稳定版本，方便后端人员直接上手开发管理平台,
2.可以尝试类似插件的形式，由用户控制是否打开，用于避免兼容性问题

非常感谢

**Comment by yoZerY** [comment]
希望能出一个

**Comment by windok2004** [comment]
强烈建议出一个，或者教怎么加入tagsview模块。

**Comment by wk1127** [comment]
从集成版本把代码复制过去就可以了,亲测可以

**Comment by wmhello** [comment]
@Eter365 @yoZerY @windok2004 @wk1127 @canghai908 如果有这方面的疑问 大家可以加我微信（xpyzwm）交流讨论  我做过更改，可以正常的加入。

**Comment by vueadmin** [comment]
楼上就是一个卖课的，大家不要加微信

**Comment by fya0122** [comment]
这个需求还用建议吗？直接按照作者的源码的tagsview复制粘贴即可，主要是vuex里面的内容，那个最主要的

**Comment by mcc-like-thinking** [comment]
> 这个需求还用建议吗？直接按照作者的源码的tagsview复制粘贴即可，主要是vuex里面的内容，那个最主要的

你好，我粘贴作者的源码tagsview的，但是当打开多可页面时，tagsview没有横向滚动条，你有遇到这个问题吗？

**Comment by jee4a** [comment]
> > #131
> > #272
> > #325
> > #344
> > 整理了一下issue列表，关于tagsview的问题比较多，
> > 有如下建议：
> 
> 1. 可以提供一个带有tagsview稳定版本，方便后端人员直接上手开发管理平台,
>    2.可以尝试类似插件的形式，由用户控制是否打开，用于避免兼容性问题
> 
> 非常感谢

增加tagsView功能步骤：
1，修改AppMain.vue文件，新增以下内容：
`
<template>
  <section class="app-main">
    <transition name="fade-transform" mode="out-in">
      <router-view :key="key" />
      **<keep-alive :include="cachedViews">
        <router-view></router-view>
      </keep-alive>**
    </transition>
  </section>
</template>
`
`export default {
  name: 'AppMain',
  computed: {
    **cachedViews() {
      return this.$store.state.tagsView.cachedViews
    },**
    key() {
      return this.$route.path
    }
  }
}`

**Comment by Eter365** [comment]
感谢，@jee4a

**Comment by Josh119891** [comment]
补充下
当前Master版本的话，是没PERMISSION的，单纯加tagsView会显示不出来，要进Layout/TagsView/components删掉routes相关的，因为它是询问  this.$store.state.permission.routes。 
![image](https://user-images.githubusercontent.com/18020366/68574175-4b23b380-04a4-11ea-8c2a-ebf5a595b8fe.png)
![image](https://user-images.githubusercontent.com/18020366/68574215-5aa2fc80-04a4-11ea-9d98-eb4a76add699.png)

**Comment by Eter365** [comment]
@Josh119891 感谢

**Comment by lanbing4191** [comment]
@jee4a @Josh119891  谢谢分享

**Comment by ftdmao** [comment]
对标签右键操作好像会有问题

**Comment by ftdmao** [comment]
新版还要把views/redirect复制一下

**Comment by PonKing66** [comment]
> > > #131
> > > #272
> > > #325
> > > #344
> > > 整理了一下issue列表，关于tagsview的问题比较多，
> > > 有如下建议：
> > 
> > 
> > 
> > 1. 可以提供一个带有tagsview稳定版本，方便后端人员直接上手开发管理平台,
> >    2.可以尝试类似插件的形式，由用户控制是否打开，用于避免兼容性问题
> > 
> > 非常感谢
> 
> 增加tagsView功能步骤：
> 
> 1，从vue-element-admin复制文件：
> vue-admin-template\srclayout\components\TagsView.vue
> vue-admin-template\srcstore\modules\tagsView.js
> vue-admin-template\src\components\ScrollPane 文件夹
> vue-admin-template\static 文件夹
> vue-admin-template\src\lang 文件夹
> vue-admin-template\src\utils\i18n.js
> 
> 2，修改 vue-admin-template\src\layout\components\AppMain.vueAppMain.vue文件，新增以下内容：
> 
> ```
> <template>
>   <section class="app-main">
>     <transition name="fade-transform" mode="out-in">
>      
>       <keep-alive :include="cachedViews">
>         <router-view></router-view>
>       </keep-alive>
>     </transition>
>   </section>
> </template>
> ```
> 
> ```
> export default {
>   name: 'AppMain',
>   computed: {
>     cachedViews() {
>       return this.$store.state.tagsView.cachedViews
>     }/*,
>     key() {
>       return this.$route.path
>     }*/
>   }
> }
> ```
> 
> 3 ，修改vue-admin-template\src\layout\components\index.js，新增如下行：
> `export { default as TagsView } from './TagsView'`
> 
> 4，vue-admin-template\src\layout\index.vue
> 
> ```
> <template>
>   <div :class="classObj" class="app-wrapper">
>     <div v-if="device==='mobile'&&sidebar.opened" class="drawer-bg" @click="handleClickOutside" />
>     <sidebar class="sidebar-container" />
>     <div class="main-container">
>       <div :class="{'fixed-header':fixedHeader}">
>         <navbar />
>       </div>
>       <tags-view />
>       <app-main />
>     </div>
>   </div>
> </template>
> ```
> 
> `import { Navbar, Sidebar, AppMain, TagsView } from './components'`
> 
> ```
> components: {
>     Navbar,
>     Sidebar,
>     AppMain,
>     TagsView
>   },
> ```
> 
> 5，修改 vue-admin-template\src\store\getters.js，增加：
> 
> ```
> visitedViews: state => state.tagsView.visitedViews,
> cachedViews: state => state.tagsView.cachedViews,
> ```
> 
> 6，修改 vue-admin-template\src\store\index.js
> `import tagsView from './modules/tagsView'`
> 
> ```
> const store = new Vuex.Store({
>   modules: {
>     app,
>     permission,
>     settings,
>     tagsView,
>     user
>   },
>   getters
> })
> ```
> 
> 7,修改 vue-admin-template\src\main.js
> `import i18n from './lang' // Internationalization`
> 
> ```
> new Vue({
>   el: '#app',
>   router,
>   store,
>   i18n,
>   render: h => h(App)
> })
> ```

谢谢分享

**Comment by wxmouse** [comment]
太感谢了。
