### ISSUE TITLE
webpack 热跟新 提示跨域报错，未请求接口

### ISSUE THREAD

**Issue by Hideer** [PanJiaChen/vue-admin-template#350]
`Access to XMLHttpRequest at 'http://192.168.130.130:8089/sockjs-node/info?t=1556272726132' from origin 'http://localhost:8089' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

如上，请求报错，

通过在vue.config.js中添加
` setup: app => {
      app.use('*', (req, res, next) => {
        res.header('Access-Control-Allow-Origin', '*')
        next()
      })
    },`
如上配置还是没能解决

**Comment by Hideer** [comment]
@PanJiaChen 直接将你模块代码拉下来，运行就是提示socket通信跨域的警告，如下
![image](https://user-images.githubusercontent.com/31301552/56849364-01b7b080-6926-11e9-93d4-b52665f11027.png)

**Comment by vueadmin** [comment]
你是解决了么

**Comment by Hideer** [comment]
@vueadmin 在vue.config.js中将host设置陈localhost就行

**Comment by hewxwshining** [comment]
在vue.config.js中设置 devServer
devServer：{
        port: 8080,
        public: 'localhost:8080',
        host: 'localhost'
}

**Comment by Daaayyy71** [comment]
> 在vue.config.js中设置 devServer
> devServer：{
> port: 8080,
> public: 'localhost:8080',
> host: 'localhost'
> }

试过了，但是网络地址也变成了本地地址。怎么办呢
