### ISSUE TITLE
跨域请求以后获取不到返回值。

### ISSUE THREAD

**Issue by linuxMengfan** [PanJiaChen/vue-admin-template#351]
![Uploading 屏幕快照 2019-04-27 18.16.27.png…]()
跨域请求以后获取不到返回值。 看浏览器已经成功返回了数据。 但是代码中获取数据为空，是只捕捉了OPTIONS请求的原因吗？

**Comment by superhos** [comment]
跨域配置设了没有。
可以服务端设置CORS Header，或者客户端webpack设一个proxy。

**Comment by linuxMengfan** [comment]
设置了  都能跨域获取到值了

**Comment by superhos** [comment]
看看console有没有error，值是只要api正常跨不跨域都能返回的，但是跨域设置没设好的话浏览器会拦截数据，在JS中无法读取。

**Comment by linuxMengfan** [comment]
> 看看控制台有没有错误，值是只要API正常跨不跨域都能返回的，但是跨域设置没设好的话浏览器会拦截数据，在JS中无法读取。

我这边过了一个晚上 没有改代码。。又能正常获取了

**Comment by superhos** [comment]
哈哈哈编程的奇妙之处

**Comment by vueadmin** [comment]
我也是这个问题，找一个以前的项目使用新接口，并没有跨域问题，不知道怎么解决
