### ISSUE TITLE
正式版[4.0]登录报错问题

### ISSUE THREAD

**Issue by MoonCheung** [PanJiaChen/vue-admin-template#354]
我本来想将这个源代码的mock修改为我自己本地Koa2服务器: [http://127.0.0.1:3030/api/login ](url) , 然后在login页面点击login按钮之后控制台提示报错的。还有另外我已经按照作者的资料对应Mock Data去做，但是这个login模块怎么解决呢，连资料也没有呢
![image](https://user-images.githubusercontent.com/19801190/57176199-696e7e00-6e87-11e9-82d9-7cdd7160eb33.png)
![image](https://user-images.githubusercontent.com/19801190/57176194-5fe51600-6e87-11e9-9cce-e0d1cf0ebce7.png)
![image](https://user-images.githubusercontent.com/19801190/57176211-a9356580-6e87-11e9-879c-3902268e1e6e.png)
![image](https://user-images.githubusercontent.com/19801190/57176253-6d4ed000-6e88-11e9-8990-89d0a9e78292.png)

**Comment by MoonCheung** [comment]
@PanJiaChen 求帮忙解答

**Comment by PanJiaChen** [comment]
报错已经很明显了。

建议先去阅读 vuex 文档，请正确使用。
