### ISSUE TITLE
 10% building 2/2 modules 0 active ERROR  SyntaxError: Unexpected string

### ISSUE THREAD

**Issue by jy1989** [PanJiaChen/vue-admin-template#358]
npm install 貌似没任何问题

npm run dev的时候报错

> 10% building 2/2 modules 0 active ERROR  SyntaxError: Unexpected string     
/Users/chen/Documents/svnproject/PJ-jxc/trunk/app/mock/index.js:1
(function (exports, require, module, __filename, __dirname) { import "core-js/modules/es6.regexp.constructor";

![image](https://user-images.githubusercontent.com/1291756/57188513-99269000-6f32-11e9-953b-0d36feef3be2.png)

**Comment by a523** [comment]
我也遇到这问题， 没人回复么？
