### ISSUE TITLE
侧边栏怎样设置永不折叠?

### ISSUE THREAD

**Issue by sn5diphone6** [PanJiaChen/vue-admin-template#360]
需求中不需要侧边栏折叠，但不知道哪里可以修改。折叠按钮的事件可以取消掉，但是浏览器界面宽度变小后侧边栏还是会自动折叠

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-admin-template/blob/master/src/layout/mixin/ResizeHandler.js
