### ISSUE TITLE
全局将VUE_APP_BASE_API 替换为BASE_API 登录时就一直404

### ISSUE THREAD

**Issue by zhuxcye** [PanJiaChen/vue-admin-template#362]
改回VUE_APP_BASE_API就没有问题，是还需要改哪里吗，有谁知道呢

**Comment by hooray** [comment]
根目录 `.env.*` 文件里配置

**Comment by vueadmin** [comment]
修改.env文件就直接跨域。。。问题同一个接口之前的版本就没有跨域问题

后端支持跨域

**Comment by vueadmin** [comment]
我都折腾一天了，佛系了

**Comment by hitore** [comment]
只有以 VUE_APP_ 开头的变量会被 webpack.DefinePlugin 静态嵌入到客户端侧的包中。你可以在应用的代码中这样访问它们：
**console.log(process.env.VUE_APP_SECRET)**
[https://cli.vuejs.org/zh/guide/mode-and-env.html#%E5%9C%A8%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BE%A7%E4%BB%A3%E7%A0%81%E4%B8%AD%E4%BD%BF%E7%94%A8%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F](url)
是这个问题吗？

**Comment by zhuxcye** [comment]
是的！ 谢谢你的解答，原来还有这一层的限制， 与上一次目录结构中的dev.env.js 不太一样了。

hitore <notifications@github.com> 于2019年5月29日周三 上午10:20写道：
