### ISSUE TITLE
Changing the primary color?

### ISSUE THREAD

**Issue by Sennar4** [PanJiaChen/vue-admin-template#367]
Is there any chance to change the primary color?
With /styles/sidebar.scss I could change the color of the sidebar.
But the rest is always in blue. 
Is there any efficient way?

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/blob/master/src/styles/element-variables.scss

https://element.eleme.cn/#/en-US/component/custom-theme
