### ISSUE TITLE
单文件测试 Element UI,  click 事件不成功 

### ISSUE THREAD

**Issue by rupertqin** [PanJiaChen/vue-admin-template#368]
https://github.com/rupertqin/vue-admin-template/commit/5f8ed4a305aa498d28cbcf26ccbfa7d449e75276
这是我测试的代码

click 事件放到 element 组件就不成功。

**Comment by PanJiaChen** [comment]
`wrapper.find('.click-button').vm.$emit('click')`

或者`<el-button  class="click-button" @click.native="listLoading=false"></el-button>`
