### ISSUE TITLE
切换用户后，缓存并未实时刷新。导致显示的是上次登录的用户信息。

### ISSUE THREAD

**Issue by chaowong** [PanJiaChen/vue-admin-template#369]
切换用户后，缓存并未实时刷新。导致显示的是上次登录的用户信息。

**Comment by chaowong** [comment]
- [ ] 

- [ ]

**Comment by chaowong** [comment]
切换用户后，缓存并未实时刷新。导致显示的是上次登录的用户信息。

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/2072

**Comment by JaimeCheng** [comment]
我也发现这问题，登录admin后在退出 再登录editor，dashboord显示的还是superadmin的信息，必须得手动刷新
