### ISSUE TITLE
改不了中文

### ISSUE THREAD

**Issue by legolas-zeng** [PanJiaChen/vue-admin-template#370]
按照文档，修改中文：
```
import locale from 'element-ui/lib/locale/lang/zh-CN' // lang i18n
```
然而并没有什么卵用，有没有大佬指点下还有哪里要改的？

**Comment by hundunzhidian** [comment]
同问，这样更改无效

**Comment by PanJiaChen** [comment]
请看官方文档。

**Comment by legolas-zeng** [comment]
已经一字一句看过来了。然后网上也看过别人改的，一样没反应，打开还是英文界面。

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-admin-template/blob/b6753d0373242afa110995583e68b230ed4bc4a3/src/main.js#L32

**Comment by hundunzhidian** [comment]
> https://github.com/PanJiaChen/vue-admin-template/blob/b6753d0373242afa110995583e68b230ed4bc4a3/src/main.js#L32

代码是这个，没有改动过

**Comment by PanJiaChen** [comment]
`Vue.use(ElementUI)` //中文写法

**Comment by liangzhiming** [comment]
template的菜单好像没做国际化，可以对比下 vue-element-admin 中国际化的方法时这样的`:title="generateTitle(onlyOneChild.meta.title)"`  generateTitle方法在vue-element-admin项目的`import { generateTitle } from '@/utils/i18n'`有定义，而template项目中没有，所以如果要把菜单改为中文的话可以直接改route里面的meta.title， 当然如果需要国际化的话也可以把import { generateTitle } from '@/utils/i18n'引入进来

**Comment by Xanthuim** [comment]
so，到底行不行呢？

**Comment by xiongyubin** [comment]
// set ElementUI lang to EN
// Vue.use(ElementUI, { locale })
// 如果想要中文版 element-ui，按如下方式声明
Vue.use(ElementUI)


一样、 上面注释了， 用了下面的、仍然是英文

**Comment by yihuiluo235** [comment]
![image](https://user-images.githubusercontent.com/2733701/79952411-f6ea1a00-84ac-11ea-9cab-9fc67c401070.png)
肯定是英文啊，他本来就没做国际化

**Comment by taruigu** [comment]
把 import locale from 'element-ui/lib/locale/lang/en' // lang i18n 注释掉：
// import locale from 'element-ui/lib/locale/lang/en' // lang i18n
然后把 Vue.use(ElementUI, { locale }) 注释掉：
// Vue.use(ElementUI, { locale })
再把 //Vue.use(ElementUI) 放出来：
Vue.use(ElementUI)
这样之后呢，element-ui组件就已经是中文的了，打开表单中的时间控件看看就明白了。但是呢，其他的地方改成中文，上面@liangzhiming老哥已经给出答案了

**Comment by Anjinc188** [comment]
我也是醉了  是不是国人开发的  居然不支持英文！

**Comment by shuxhan** [comment]
这里改的好像只是一些组件的中文化，template貌似不支持全局中文化，我是直接在路由里面修改侧边栏的名称

**Comment by arcoshin** [comment]
//我在main.js引入內建的繁體中文包
import zh_tw_Lang from 'element-ui/lib/locale/lang/zh-TW';  //zh_tw_Lang 可以自定義名稱

//接著在讓Vue框架自動使用
Vue.use(ElementUI, {
    locale: { ...zh_tw_Lang }, // 使用本地的 zh_tw_Lang 語言包
});


其中ElementUI也算是一個自定義的變量名
//由於我開頭聲明導入element-ui為"ElementUI"變量(import ElementUI from 'element-ui';) 
//因此括號內的調用必須使用自己定義的變量名稱"ElementUI"
//locale則是對應的語言包所在的組件包名，這是固定的

如此就可以輕鬆調用內建的語言包
自定義中有zh-CN應該也比照上面可以輕鬆轉換
