### ISSUE TITLE
更新以后就无限制的跨域

### ISSUE THREAD

**Issue by vueadmin** [PanJiaChen/vue-admin-template#380]
已经尝试一天了

所以有能力还是自己撸一个吧

**Comment by vueadmin** [comment]
都是一套API，后端也支持跨域，回退到老版本就没有问题，用新版本就各种跨域，折腾一天，佛系了。

希望作者回退一下。

**Comment by PanJiaChen** [comment]
请提供详细信息。

**Comment by vueadmin** [comment]
![image](https://user-images.githubusercontent.com/18540773/58412884-fcc35980-80a9-11e9-80ea-13dbc02a9a80.png)
![image](https://user-images.githubusercontent.com/18540773/58412897-064cc180-80aa-11e9-894e-acffd970636e.png)

**Comment by vueadmin** [comment]
@PanJiaChen  后端代码不变，使用以前的版本，直接没有任何问题

一只不明白什么导致的，前端各种配置来回组合切换

**Comment by vueadmin** [comment]
切换项目
![image](https://user-images.githubusercontent.com/18540773/58413113-98ed6080-80aa-11e9-94ed-d2215d0746bb.png)

**Comment by vueadmin** [comment]
新版本options请求结束后就提示跨域了，但是切换到之前的版本，直接就登录进去，这个login请求返回作者应该很熟悉了

难道我要整理一分之前的版本，长期使用？

**Comment by vueadmin** [comment]
![image](https://user-images.githubusercontent.com/18540773/58414278-7c9ef300-80ad-11e9-83d5-cf6600d6c837.png)
也可能是我pei配置有问题 
我发一下我尝试的所有配置方式

这么配置请求地址永远都是本地 不是配置的地址

![image](https://user-images.githubusercontent.com/18540773/58414313-93454a00-80ad-11e9-9068-09df5669c12f.png)

**Comment by vueadmin** [comment]
如果我在.env配置
![image](https://user-images.githubusercontent.com/18540773/58414379-ca1b6000-80ad-11e9-9c9b-af41d2b1f911.png)
虽然请求地址对了 但是会提示我跨域 option请求没有问题

但是根据我上面的截图 直接更换以前版本 没有跨域问题

![image](https://user-images.githubusercontent.com/18540773/58414416-e919f200-80ad-11e9-8951-7926225e79b5.png)

**Comment by vueadmin** [comment]
https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/mock-api.html#%E6%9C%AC%E5%9C%B0-mock-%E6%95%B0%E6%8D%AE%E4%B8%8E%E7%BA%BF%E4%B8%8A%E6%95%B0%E6%8D%AE%E5%88%87%E6%8D%A2

根据文档，没有办法避开跨域问题

后端也无法解决跨域问题

有哥们用新版本解决了跨域问题么

求解决方案

跪谢

**Comment by vueadmin** [comment]
想到一种可能，是不是mock数据并没有禁止成功，options请求发送成功以后，并没有发送post请求

我去研究一下

**Comment by PanJiaChen** [comment]
你对 proxy 有误解吧。

**Comment by PanJiaChen** [comment]
你的 `http://wechat-token-api` 不应该写在`VUE_APP_BASE_API`中，应该新建一个。

**Comment by vueadmin** [comment]
#381
