### ISSUE TITLE
v4.0+版本打包后API部分请求报错

### ISSUE THREAD

**Issue by 77tao** [PanJiaChen/vue-admin-template#382]
v4.0+版本打包后API部分请求报错并且控制台没有查看到请求
![image](https://user-images.githubusercontent.com/35914601/58459159-4e78ec00-815d-11e9-9ad9-2de9035a4c54.png)
上图为本地地址
![image](https://user-images.githubusercontent.com/35914601/58459221-75cfb900-815d-11e9-9864-ffaf8a1e6610.png)
![image](https://user-images.githubusercontent.com/35914601/58459271-90099700-815d-11e9-8f7c-685e3c608f9c.png)
上图为预览地址控制台抛出错误

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-admin-template/blob/737d9fc9ee40ba0c8e8c51a5e687ac1a4b95285a/src/main.js#L26-L29

mock 注释了么？

**Comment by 77tao** [comment]
注释掉就好了，感谢大佬！
