### ISSUE TITLE
重写api之后，已从后台拿到返回值了，但是页面跳转无反应是什么原因呢？？

### ISSUE THREAD

**Issue by whatkind** [PanJiaChen/vue-admin-template#385]
![image](https://user-images.githubusercontent.com/35456622/58633903-6fd40680-831c-11e9-8abf-9ffa90874841.png)

** api/login
![image](https://user-images.githubusercontent.com/35456622/58633963-9a25c400-831c-11e9-999e-245ce3ad809d.png)

route index没有改变

**Comment by whatkind** [comment]
![image](https://user-images.githubusercontent.com/35456622/58634231-51bad600-831d-11e9-9ac0-2a00d720224e.png)

点击登陆后，浏览器地址栏的效果

**Comment by hyz23je** [comment]
看一下你自己拿到的返回值的格式是否对了。你可以参数一下mock里面的返回值的格式

**Comment by miaogulu** [comment]
我之前也是这个问题，最后发现是token的问题
