### ISSUE TITLE
找不到动态配置的组件

### ISSUE THREAD

**Issue by litete** [PanJiaChen/vue-admin-template#399]
我自己写的根据后端的返回配置左侧导航栏的代码中，根据返回的url拼接component，在运行后提示“vue-router.esm.js:1921 Error: Cannot find module '@/views/attest/check'”，求大神解答
 相关代码：children.forEach(child => {
        var childNode = {
          path: child.url,
          name: child.name,
         component: () => import('@/views' + child.url),
          meta: { title: child.name, icon: child.icon },
          buttons: child.buttons
        }
        console.log(childNode.path)
        level.children.push(childNode)
      })
如果还需要别的地方的代码，请告我，我贴出来

**Comment by litete** [comment]
已解决

**Comment by He0cool** [comment]
> 已解决

请问一下，你是这么解决的啊，拼接component是写在permission.js里面吗
