### ISSUE TITLE
config目录跑哪里去了？

### ISSUE THREAD

**Issue by yuyueqty** [PanJiaChen/vue-admin-template#400]
之前的版本有config目录，可以配置不同的环境，现在config目录不见了，请问后端服务地址在哪里配置？

**Comment by Zuohao1994** [comment]
根目录下面，`.env.development` 开头的几个文件。VUE-CLI 3.0 过一遍就没疑问了。

**Comment by yuyueqty** [comment]
之前的版本修改这个文件不起作用，现在已经好了。
