### ISSUE TITLE
跪求解决run dev报错 Module build failed (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):

### ISSUE THREAD

**Issue by wxb1123603312** [PanJiaChen/vue-admin-template#419]
![image](https://user-images.githubusercontent.com/12553762/60609225-c76e0200-9df3-11e9-996c-c07e3128dc46.png)

**Comment by jp3049** [comment]
https://github.com/vuejs/vue-cli/issues/4231
