### ISSUE TITLE
新版有没有带权限控制的版本同步更新？

### ISSUE THREAD

**Issue by yichangle** [PanJiaChen/vue-admin-template#42]
貌似权限控制版本没有更新，能否同步更新权限版本呢？谢谢！

**Comment by PanJiaChen** [comment]
vueAdmin 不涉及路由权限。

**Comment by yichangle** [comment]
我可能没说清楚，我指的是以前版本中存在，后来删除了的，依据后台传过来的权限，动态显示左侧菜单的功能。

**Comment by PanJiaChen** [comment]
恩 默认不会提供这些代码了，有需求的可以解决 vue-element-admin 的写法
