### ISSUE TITLE
打包之后项目项目一直报405

### ISSUE THREAD

**Issue by zhuxuda** [PanJiaChen/vue-admin-template#423]
您好，请问为什么这个项目本地跑是正常的没有问题，但是打包之后无论在本地使用http-server还是部署到服务器上都会报405的错误？什么方法都试过了

**Comment by zhuxuda** [comment]
您可以试一下不用mock 打包之后请求一下真正的接口吗 @PanJiaChen

**Comment by PanJiaChen** [comment]
已修复，https://github.com/PanJiaChen/vue-admin-template/pull/541

重新拉一下代码
