### ISSUE TITLE
请教一下，想改成多页面时，打包后提示runtime.js找不到，该怎么配置vue-cli,

### ISSUE THREAD

**Issue by finyo** [PanJiaChen/vue-admin-template#432]
![image](https://user-images.githubusercontent.com/23208697/61194886-3c481280-a6f7-11e9-84a3-afb44378a83b.png)
![image](https://user-images.githubusercontent.com/23208697/61194903-5eda2b80-a6f7-11e9-9b05-4c19dc7634d7.png)

**Comment by finyo** [comment]
已解决。感谢开源

**Comment by lppsuixn** [comment]
@finyo 请问怎么解决的？

**Comment by finyo** [comment]
发自我的 iPhone

**Comment by mygoodidea** [comment]
@finyo 请问怎么解决的

**Comment by hoganjobs** [comment]
@finyo 可以分享下怎么解决的吗，感谢

**Comment by Codezero123** [comment]
请教一下怎么解决了，谢谢了，

**Comment by Codezero123** [comment]
> 已解决。感谢开源

大哥 指点一下谢谢了

**Comment by finyo** [comment]
发自我的iPhone

**Comment by lzq777** [comment]
因为webpack2不能同时使用import和module.export所以打包报错了，可以用babel把es6和commonJS严格区分,具体解决方法在`babel.config.js`配置
```javascript
module.exports =
{
  presets: ['@vue/app'],
  sourceType: 'unambiguous'
}
```
`unambiguous`将使得`babel`尝试根据es6的`import`和`export`声明来推测是`module`文件，其他的则当成`script`文件
