### ISSUE TITLE
那个Dashboard页面是必须存在的吗

### ISSUE THREAD

**Issue by Takicheng** [PanJiaChen/vue-admin-template#435]
![image](https://user-images.githubusercontent.com/42823161/61576298-06e26100-ab0b-11e9-8d44-fa2c466c439e.png)
我想点form的时候面包屑上就是form
下面的链接不是在 Dashboard/ 下

**Comment by microkof** [comment]
这个容易，去components的面包屑.vue里把
```
      if (!this.isDashboard(first)) {
        matched = [{ path: '/dashboard', meta: { title: 'Dashboard' }}].concat(matched)
      }
```
注释掉。
