### ISSUE TITLE
请问下我要前后端分离，这个depatch怎么绑定后台的URL

### ISSUE THREAD

**Issue by xx-zhang** [PanJiaChen/vue-admin-template#436]
- 我已经舍弃和删除了 mockjs
- user-login 
[user/login](https://github.com/PanJiaChen/vue-admin-template/blob/master/src/views/login/index.vue#L112)

我设置了 `VUE_APP_BASE_API` 所以它重定向到了 http://localhost:3322/user/login 

- .env.development 
```
# just a flag
ENV = 'development'

# base api
# VUE_APP_BASE_API = '/dev-api'
VUE_APP_BASE_API = 'http://localhost:3322/'
```

请问下 怎么修改 store 使得URL能够访问到我自己的 `http://localhost:3322/accounts/jwt_login `

**Comment by xx-zhang** [comment]
自问自答  修改 user,js 里面的URL即可

**Comment by lihua123569** [comment]
VUE_APP_BASE_API = 'http://localhost:3322/'
就设置这个就行了吗？还有其他地方要设置吧，我这边设置了，network地址还是调用的localhost:9528,还是本地前端的vue项目地址
