### ISSUE TITLE
端口不是 9528

### ISSUE THREAD

**Issue by lijiansgit** [PanJiaChen/vue-admin-template#458]
https://github.com/PanJiaChen/vue-element-admin/issues/2492 问题一样，哪个版本导致的呢

**Comment by mzh1994s** [comment]
同问，我的端口是随机的

**Comment by mzh1994s** [comment]
> [PanJiaChen/vue-element-admin#2492](https://github.com/PanJiaChen/vue-element-admin/issues/2492) 问题一样，哪个版本导致的呢

 @ArcherGu：npm install portfinder@1.0.21，再正常[c]npm i

**Comment by ghgh1995** [comment]
问题一样，端口号是随机的

**Comment by lijiansgit** [comment]
解决了。删除node_modules下面的portfinder包，修改package.json，在devDependencies中增加"portfinder": "1.0.21",然后npm install 。参考：https://github.com/PanJiaChen/vue-element-admin/issues/2492
