### ISSUE TITLE
语言怎么设置成中文

### ISSUE THREAD

**Issue by plutoPG** [PanJiaChen/vue-admin-template#491]
按照网上的方法改main.js文件里的内容,但是没有用

**Comment by Xanthuim** [comment]
同问，都不知道作者在干啥。。

**Comment by wmhello** [comment]
这种简单的问题  真的没有回答的必要

**Comment by wmhello** [comment]
提醒一下  去看element UI的文档

**Comment by wmhello** [comment]
还有 需要更多的辅导  可以加我微信(xpyzwm)

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-admin-template/blob/35ea50deea84fb0b42c0246810ea08c3c5c70023/src/main.js#L31-L34

**Comment by chezhenlei** [comment]
> https://github.com/PanJiaChen/vue-admin-template/blob/35ea50deea84fb0b42c0246810ea08c3c5c70023/src/main.js#L31-L34

改了，为什么不起作用

**Comment by toplyb** [comment]
> https://github.com/PanJiaChen/vue-admin-template/blob/35ea50deea84fb0b42c0246810ea08c3c5c70023/src/main.js#L31-L34

并不行, 已经尝试过了, 仍然没有修改成功语言
