### ISSUE TITLE
el-datepicker bug

### ISSUE THREAD

**Issue by upcwangying** [PanJiaChen/vue-admin-template#496]
![AB1(4FCAK(N_IJ ~ V29 O8](https://user-images.githubusercontent.com/19725091/67564066-b3f4f700-f754-11e9-9d02-3ee418fa8338.png)

version： `4.2.1`

1. `range-separator` 显示不全
2. 选择日期后，没有居中

```
<el-date-picker
      v-model="value6"
      type="daterange"
      size="small"
      range-separator="至"
      start-placeholder="开始日期"
      end-placeholder="结束日期">
    </el-date-picker>
```

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-admin-template/commit/dc5aa51577c4e432ff59fd711c1d2de99220993e
