### ISSUE TITLE
isDashboard 疑问

### ISSUE THREAD

**Issue by 123114** [PanJiaChen/vue-admin-template#498]
isDashboard(route) {
      const name = route && route.name
      if (!name) {
        return false
      }
      return name.trim().toLocaleLowerCase() === 'Dashboard'.toLocaleLowerCase()
    },
这里的 name 是怎么赋值的呀  ，第二行不是返回 true/false  ,  那 第6行 name值是什么

**Comment by 66beta** [comment]
短路操作
```js
const route = { name: 'dashboard' };
const name = route && route.name; /* name => 'dashboard' */
```
