### ISSUE TITLE
一级导航下挂多个外链时异常

### ISSUE THREAD

**Issue by forilen** [PanJiaChen/vue-admin-template#513]
示例代码中，若在 path: 'external-link' 的children中加入多个外链路由，会出现路由解析错误，返回404

**Comment by PanJiaChen** [comment]
我试了下没重现你的问题，能贴下错误代码么？

**Comment by forilen** [comment]
> 我试了下没重现你的问题，能贴下错误代码么？

抱歉，可能是我用的版本比较旧。测试了一下最新的master分支，没有这个问题，谢谢
