### ISSUE TITLE
安装好依赖后，浏览器打开，点击登录报错405

### ISSUE THREAD

**Issue by chenzhenglin** [PanJiaChen/vue-admin-template#526]

**Comment by csdoker** [comment]
我也是这样。。。

**Comment by chenzhenglin** [comment]
把mock-server模块去掉直接使用mockjs是可以的，使用自带的mock-server报错不支持POST，估计是服务内部有啥问题，准备自己搭一个简易的mock-server

**Comment by fanchaot** [comment]
怎么解决。。。  看着依赖的东西 有很多

**Comment by emergencyJob** [comment]
> 我也是这样。。。
我的做法是把 post请求改成get 请求，上网查了一下好像是说对于静态资源的请求不支持post,改成get请求之后还需要修改参数   params: { username:data.username }

**Comment by csdoker** [comment]
@emergencyJob 
那这样不是

> > 我也是这样。。。
> > 我的做法是把 post请求改成get 请求，上网查了一下好像是说对于静态资源的请求不支持post,改成get请求之后还需要修改参数   params: { username:data.username }

那这样的话。。岂不是不能用post的方式请求了。。。治标不治本啊。。为啥作者还没改这种方式呢

**Comment by emergencyJob** [comment]
> > > 我也是这样。。。
> > > 我的做法是把 post请求改成get 请求，上网查了一下好像是说对于静态资源的请求不支持post,改成get请求之后还需要修改参数   params: { username:data.username }
> 
> @emergencyJob
> 那这样的话。。岂不是不能用post的方式请求了。。。治标不治本啊。。为啥作者还没改这种方式呢

嗯   作为一个后端  我确实看不来这东西  还是等作者更新吧 先改成get跑起来往下走嘛

**Comment by emergencyJob** [comment]
> > > > 我也是这样。。。
> > > > 我的做法是把 post请求改成get 请求，上网查了一下好像是说对于静态资源的请求不支持post,改成get请求之后还需要修改参数   params: { username:data.username }
> > 
> > 
> > @emergencyJob
> > 那这样的话。。岂不是不能用post的方式请求了。。。治标不治本啊。。为啥作者还没改这种方式呢
> 
> 嗯 作为一个后端 我确实看不来这东西 还是等作者更新吧 先改成get跑起来往下走嘛

我尝试把vue.config.js里面的 127.0.0.1改成 localhost   成功了  你可以试一下  最后一次代码提交是改了这块

**Comment by brightstarlcg** [comment]
登录报错405 Method Not Allowed,post方法不支持啊要怎么添加

**Comment by brightstarlcg** [comment]
> > > > > 我也是这样。。。
> > > > > 我的做法是把 post请求改成get 请求，上网查了一下好像是说对于静态资源的请求不支持post,改成get请求之后还需要修改参数   params: { username:data.username }
> > > 
> > > 
> > > @emergencyJob
> > > 那这样的话。。岂不是不能用post的方式请求了。。。治标不治本啊。。为啥作者还没改这种方式呢
> > 
> > 
> > 嗯 作为一个后端 我确实看不来这东西 还是等作者更新吧 先改成get跑起来往下走嘛
> 
> 我尝试把vue.config.js里面的 127.0.0.1改成 localhost 成功了 你可以试一下 最后一次代码提交是改了这块

改了也不行啊咋回事

**Comment by opticor** [comment]
这里是用mockjs就好，打开main.JS，执行mockXHR()

**Comment by PanicmonsterU** [comment]
把main.js里这两行给注释掉就行了
// if (process.env.NODE_ENV === 'production') {
  mockXHR()
// }

**Comment by sjx1995** [comment]
只请求方式和mock的接收参数改为GET，会报错“Account and password are incorrect.”

然后修改mock/user.js中的登录token为`token = { token: 'admin-token' }`，就好了

**Comment by xuxian02092213** [comment]
mock\index.js中
Mock.mock(new RegExp(i.url), i.type || 'get', XHR2ExpressReqWrap(i.response))
修改为
Mock.mock(new RegExp(i.url), XHR2ExpressReqWrap(i.response))
大家参考下Mock.mock方法

**Comment by sumforest** [comment]
> 把main.js里这两行给注释掉就行了
> // if (process.env.NODE_ENV === 'production') {
> mockXHR()
> // }

这方法有效，感谢

**Comment by packjie** [comment]
在main.js中改成下面这样子有效
if (process.env.NODE_ENV === 'production') {//留下来做生产环境的判断
  mockXHR()
}else{
  mockXHR()
}

**Comment by PanJiaChen** [comment]
已修复，https://github.com/PanJiaChen/vue-admin-template/pull/541

重新拉一下代码
