### ISSUE TITLE
初次运行就报 405，登录不进去，是哪里错了

### ISSUE THREAD

**Issue by yeahliv** [PanJiaChen/vue-admin-template#530]
![微信截图_20191227111608](https://user-images.githubusercontent.com/34160612/71499366-1d030300-289b-11ea-8134-003b3265cf14.png)

**Comment by telangpu** [comment]
main.js 把 mockXHR() 拿到外头

**Comment by genzj** [comment]
@telangpu  方法有效，感谢。但是我还是比较中意作者给出的mock-server新方案，所以继续查了下。

应该是注册mock-server的位置比较靠后（在`after`回调内注册），因此mock相关的路径已经被前面某个Layer处理了（返回405）。尝试了把注册位置提到`before`中，发现会因为`router.use(bodyParser.json())`调用太早而导致webpack dev server在proxy时无法转发body （[issue](https://github.com/http-party/node-http-proxy/issues/1279)）。

于是继续修改了`mock-server.js`，将mock所用中间件和路径隔离到了一个`Router`中。提了PR#533

**Comment by yunhuduan** [comment]
解决方案请看此处:https://github.com/PanJiaChen/vue-element-admin/issues/2897#issuecomment-569946355

**Comment by PanJiaChen** [comment]
已修复，https://github.com/PanJiaChen/vue-admin-template/pull/541

重新拉一下代码
