### ISSUE TITLE
如何设置左侧子菜单默认全部打开

### ISSUE THREAD

**Issue by lmfuture** [PanJiaChen/vue-admin-template#538]
如何设置左侧子菜单默认全部打开

**Comment by csccoder** [comment]
1.edit  src#layout#components#Sidebar#index.vue 
2.find el-menu tag，add **default-openeds** attr. attr value is router str array of need to default open 
` <el-menu
        :default-openeds="openeds"
      >`

**Comment by PanJiaChen** [comment]
https://panjiachen.github.io/vue-element-admin-site/zh/guide/essentials/router-and-nav.html#%E4%BE%A7%E8%BE%B9%E6%A0%8F%E9%BB%98%E8%AE%A4%E5%B1%95%E5%BC%80
