### ISSUE TITLE
接口配置正确, 返回 error

### ISSUE THREAD

**Issue by dodu2014** [PanJiaChen/vue-admin-template#539]
login 接口配置正确, 控制台 network 里面状态200, 但 store/ modules/user.js, 调用 login方法 执行 catch

**Comment by PiaoRongZhen** [comment]
我也是同样的问题，楼主最后怎么解决的

**Comment by dodu2014** [comment]
> 我也是同样的问题，楼主最后怎么解决的

还是自己的问题, 仔细检查一下 axios 的封装.
