### ISSUE TITLE
登录页无法正常跳转登录/Request failed with status code 405

### ISSUE THREAD

**Issue by dongdong0524** [PanJiaChen/vue-admin-template#540]
第一天可以正常登录，第二天在登录页面就无法登录了，提示Request failed with status code 405，开始以为是项目问题，去官网重新下载了一个启动，还是报同样的错误，试着修改为get请求，还是报错，不知道是哪里出了问题

**Comment by PanJiaChen** [comment]
已修复，https://github.com/PanJiaChen/vue-admin-template/pull/541

重新拉一下代码
