### ISSUE TITLE
Unknown custom element: <el-divider> - did you register the component correctly? For recursive components, make sure to provide the "name" option

### ISSUE THREAD

**Issue by solopromiguel** [PanJiaChen/vue-admin-template#542]
Hello community, I have the drawback with some components, when adding them the following message appears

`vue.runtime.esm.js:599 [Vue warn]: Unknown custom element: <el-divider> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

未知的自定義元素：<el-divider>-您是否正確註冊了組件？對於遞歸組件，請確保提供“名稱”選項

This is not only with the <el-divider>, but also with others, I am using the template

thanks for your help

**Comment by PanJiaChen** [comment]
更新一下 element-ui版本就好了。老版本没有这个组件。
