### ISSUE TITLE
字体文件加载失败

### ISSUE THREAD

**Issue by Mestarry** [PanJiaChen/vue-admin-template#544]
downloadable font: download failed (font-family: "element-icons" style:normal weight:400 stretch:100 src index:0): status=2152398866 source: chrome-extension://ckkcogedanhgeifldcjgnodgdcfhiben/fonts/element-icons.woff

**Comment by Mestarry** [comment]
svg文件问题

**Comment by Musashi11** [comment]
Hi, This problem has been resolved?  Can you provide solution?
