### ISSUE TITLE
_import = require('./_import_' + process.env.NODE_ENV)  

### ISSUE THREAD

**Issue by zhaojinxiong** [PanJiaChen/vue-admin-template#55]
这个是什么意思呀~
component: () => import('@/views/login/index')
_import('excel/exportExcel')

我是参照 admin 那项目 中有_import = require('./_import_' + process.env.NODE_ENV)  
copy过来却报错了~
This relative module was not found:

**Comment by JerryMissTom** [comment]
这个应该是判断打包环境决定组件是否采用懒加载的方式，假如是production，则懒加载，假如是dev，则不采用懒加载。因为懒加载时热更新比较慢，改代码后看效果等待太久，作者在自己的文章中也说了这个。
