### ISSUE TITLE
vue-router自定义属性

### ISSUE THREAD

**Issue by JerryMissTom** [PanJiaChen/vue-admin-template#56]
在vue-router中我只看到路由元信息，即meta的设置，但是在你的代码中出现了hidden, alwaysShow等自定义属性。我在Vue-Router的构造配置中并未找到相关可设置字段，请问这个设置有什么相关资料可以参考么？

**Comment by PanJiaChen** [comment]
使用的都是自定义属性，你也可以自定义。
详情见[文档](https://panjiachen.github.io/vue-element-admin-site/#/zh-cn/router-and-nav)

**Comment by PanJiaChen** [comment]
meta里面所有自定义属性都支持。除此之外的自定义属性在$route上市获取不到的。而`hidden`或者`alwaysShow`只是针对导航使用，在导航中直接将引用的routeMap,没有使用`vue-route` 所有不造成影响。

**Comment by JerryMissTom** [comment]
明白了，谢谢
