### ISSUE TITLE
npm run build:stage 打包后样式错乱问题

### ISSUE THREAD

**Issue by jiaohuang1983** [PanJiaChen/vue-admin-template#568]
npm run build:stage 打包后样式错乱了，左侧菜单是根据权限动态加载进来的，样式就乱了，如果左侧点菜单写死的，打包后样式没有问题，想进webpack.prod.conf.js改下配置文件，但是没有找到这个文件。请问有遇到这个问题的吗？

**Comment by jiaohuang1983** [comment]
虽然还是没弄明白 为啥路由写死打包没问题 动态路由有问题，但是现在问题解决了。解决办法：根HTML的类名每个页面保持唯一。虽然会多一个重复的没打包的样式，但是也不影响了。

**Comment by ziyoren** [comment]
理解一下 style的scoped

发自我的iPhone
