### ISSUE TITLE
无法配置中文版

### ISSUE THREAD

**Issue by chouxiaozi1989** [PanJiaChen/vue-admin-template#574]
按照main.js中的配置改为中文版声明后，run dev仍然为英文版

**Comment by Joey-996** [comment]
> 按照main.js中的配置改为中文版声明后，run dev仍然为英文版

兄弟  你解决了吗，我也发现这个问题了，之前用好像没有的

**Comment by chouxiaozi1989** [comment]
> > 按照main.js中的配置改为中文版声明后，run dev仍然为英文版
> 
> 兄弟 你解决了吗，我也发现这个问题了，之前用好像没有的

没有呢。。。。。不清楚是什么原因，i18n分支好像是可以，但是master貌似不行

**Comment by PanJiaChen** [comment]
你指的中英文是指什么？
你指login dashboard的话，不支持，
`vue-admin-template` 本身就没有太多内容，自己改一下就好了。

**Comment by lipan-xidian** [comment]
配置中文不生效，各位大佬解决这个问题了嘛

**Comment by lipan-xidian** [comment]
> > > 按照main.js中的配置改为中文版声明后，run dev仍然为英文版
> > 
> > 
> > 兄弟 你解决了吗，我也发现这个问题了，之前用好像没有的
> 
> 没有呢。。。。。不清楚是什么原因，i18n分支好像是可以，但是master貌似不行

i18n基础版本没有啊，只有完整版本才有这个分支

**Comment by xixiyuguang** [comment]
这个配置中文是element-ui的配置中文，所以只是el的组件包含中文，其他的页面肯定还是英文了
