### ISSUE TITLE
在权限模版下 对路由添加path参数/:id?  侧边渲染时候会出现一个bug

### ISSUE THREAD

**Issue by chenweibo** [PanJiaChen/vue-admin-template#578]
侧边默认应该没参数应该为空 但是生成了字符
<img width="636" alt="Snipaste_2020-05-08_17-24-52" src="https://user-images.githubusercontent.com/19586007/81392293-0a55e000-9151-11ea-9589-f1756342da91.png">
<img width="1196" alt="Snipaste_2020-05-08_17-25-35" src="https://user-images.githubusercontent.com/19586007/81392318-12ae1b00-9151-11ea-9403-d737379027f0.png">

**Comment by PanJiaChen** [comment]
侧边栏不支持。
你本身就是个伪需要吧，侧边栏会什么会支持动态路由参数？
