### ISSUE TITLE
打包后路由懒加载失效，只生成一份app.js

### ISSUE THREAD

**Issue by XingeWang** [PanJiaChen/vue-admin-template#584]
原有打包效果会生成js文件夹，里面是多份hash js文件（按照路由划分），现在打包完只生成一份app.js，可能是哪些配置引起的呢

**Comment by BenXi630** [comment]
怎么解决的

**Comment by zzp0373** [comment]
怎么解决的？

**Comment by XingeWang** [comment]
我是信鸽，您的邮件已成功押送至我的山寨，谢谢了

**Comment by zzp0373** [comment]
能否留一个联系方式，跪求解决方案

**Comment by XingeWang** [comment]
> 能否留一个联系方式，跪求解决方案

不晓得你解决没，我忘了怎么解决的了。核心排查思路我记得是先把vue.config.js用回初始的，看看打包出来行不行，不行就在初始工程中把我的代码一大块一大块的挪进去，然后打包测试加了哪块打包就异常，再去排查问题，当时是这样的思路最终就找到了问题
