### ISSUE TITLE
npm run build:prod 编译后的文件本地跑起来报错 TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by ddsong** [PanJiaChen/vue-admin-template#589]
编译后放本地环境，访问时报错，有人遇到吗？

**Comment by foxchen** [comment]
有啊，，，我也是最近刚开始打算用这个，不管这个还是admin，打包都是会报错，问了百度半天说是exports跟import混用了，不过我也没找到啊，

**Comment by PanJiaChen** [comment]
线上最新版本？

**Comment by foxchen** [comment]
> 线上最新版本？

是的啊，我是直接下的zip包。。。

**Comment by foxchen** [comment]
> 线上最新版本？

群里有个兄弟让我在babel.config.js里面加了个sourceType:'unambiguous'，打包完就可以运行了。。

**Comment by ddsong** [comment]
> > 线上最新版本？
> 
> 群里有个兄弟让我在babel.config.js里面加了个sourceType:'unambiguous'，打包完就可以运行了。。

是么，我也试试

**Comment by PanJiaChen** [comment]
https://github.com/PanJiaChen/vue-element-admin/issues/3271
