### ISSUE TITLE
在该框架下使用vue-video-player +videojs-contrib-hls.js播放器播放hls视频，在开发环境下可以正常使用，生产环境下报错。

### ISSUE THREAD

**Issue by Jscong** [PanJiaChen/vue-admin-template#603]
在该框架下使用vue-video-player +videojs-contrib-hls.js播放器播放hls视频，在开发环境下可以正常使用，生产环境下报错。具体报错如下：
Uncaught TypeError: Cannot read property 'readyState' of null
    at XhrLoader.readystatechange (hls.js?ba56:10889)
    at MockXMLHttpRequest.dispatchEvent (mock.js?96eb:8472)
    at XMLHttpRequest.handle (mock.js?96eb:8300)

对应的代码行报错如下：
hls.js：
XhrLoader.prototype.readystatechange = function readystatechange(event) {
    var xhr = event.currentTarget,
        readyState = xhr.readyState,
        stats = this.stats,
        context = this.context,
        config = this.config;

请问有没大神帮忙解决一下该问题？谢谢

**Comment by PanJiaChen** [comment]
在 index.js 注销mockjs
