### ISSUE TITLE
动态路由

### ISSUE THREAD

**Issue by Calvin1121** [PanJiaChen/vue-admin-template#617]
首次登陆后可以拿到路由列表,刷新之后路由列表为空;
首次进入动态页面正常显示,刷新之后页面空白
求大佬告知.谢谢
![e04ec07860f9b182fe6254ec1fbda2f](https://user-images.githubusercontent.com/31435496/90854766-6f57dd80-e3b0-11ea-828f-b460c46444c0.png)
![45cbf3557cdbc7839e89cd6a9900e85](https://user-images.githubusercontent.com/31435496/90854775-7252ce00-e3b0-11ea-9a36-615762742eee.png)
![734fa98bfb0212e59865228f88aa240](https://user-images.githubusercontent.com/31435496/90854779-741c9180-e3b0-11ea-97d1-38624795813b.png)
![9ebc648bcbce6e0ba2877e57e9a8ea4](https://user-images.githubusercontent.com/31435496/90854785-767eeb80-e3b0-11ea-8623-43cb7e7908c7.png)
![40496d8e53e636cb4733a0c1d7b4f5f](https://user-images.githubusercontent.com/31435496/90854791-7979dc00-e3b0-11ea-84f9-ef2f322eddef.png)

**Comment by Calvin1121** [comment]
搞好了

**Comment by FuYiCai** [comment]
我也是这个问题，请问怎么解决呢
