### ISSUE TITLE
npm install失败报错

### ISSUE THREAD

**Issue by BLCheung** [PanJiaChen/vue-admin-template#673]
执行npm install会报错，并且项目目录里也不存在node_modules
<img width="747" alt="WechatIMG60" src="https://user-images.githubusercontent.com/19581432/114352758-cf4cff80-9b9e-11eb-8b28-9d51b369f06f.png">

**Comment by windlychee** [comment]
我也是，而且安装依赖速度非常慢，切换淘宝源和科技都不行

**Comment by JyunkaiWang** [comment]
1、先删去node_modules
2、不使用淘宝源，如果之前设置过可以通过 `npm config delete registry` 删除
3、重新运行 `npm install`

**Comment by BLCheung** [comment]
npm不好使，我还是用yarn去解决了，yarn编译通过了
