### ISSUE TITLE
大佬您好，首先我也在使用您的仓库，感觉很棒。

### ISSUE THREAD

**Issue by chao325** [PanJiaChen/vue-admin-template#713]

**Comment by KilitoCH** [comment]
按照社区精神，人家做内容产出已经很不容易了。
其次我觉得你说的有道理，如果这个仓库使用最多的是中国人，那就需要一份中文文档。期待你的翻译~

**Comment by chao325** [comment]
> 

谢谢你的支持，如果我读英文不吃力有你能力翻译的的话，我为什么还希望有中文文档呢？我并不是索要中文文档，而是我想明白， 为什么都是用英文。

**Comment by daozun** [comment]
我觉得你可以做一份你喜欢的文档分享给大家，加油，我看好你

**Comment by chao325** [comment]
> 我觉得你可以做一份你喜欢的文档分享给大家，加油，我看好你

非常感谢您的信任，同时我也很感谢作者所产出的内容。我并没有索要文档，而是想明白为什么使用英文作为主语言写文档。我觉得任何人，任何行业，任何年纪，都有权利去学习一些他不懂的内容。而不是用自身的知识素质涵养作为自立的门槛，去要求别人也必须达到，我承认我的任何方面都没有各位强，你们所触及的高度，是我一生都可望而不可及，甚至是难以达到的水平或境界。非常感谢您的鼓励。我会继续努力的。同时也非常感谢作者的贡献！
