### ISSUE TITLE
npm run build报错

### ISSUE THREAD

**Issue by chenchao111** [PanJiaChen/vue-admin-template#74]
![image](https://user-images.githubusercontent.com/18584196/38488807-2469939c-3c17-11e8-90f2-043a9ff3514f.png)
npm run build打包的时候报错  这是什么原因啊

**Comment by PanJiaChen** [comment]
报错很明显了吧。

**Comment by 330767014** [comment]
我这也是报这个错误，请问大神，怎么回事

**Comment by PanJiaChen** [comment]
你把报错随手搜索引擎一复制就有答案了。

![image](https://user-images.githubusercontent.com/8121621/45066743-546ffe00-b0f2-11e8-9ef3-7bf42305fb4d.png)
