### ISSUE TITLE
vueAdmin-template 首页加载有502k有什么办法让加载在小一些呢

### ISSUE THREAD

**Issue by jiahaikun** [PanJiaChen/vue-admin-template#80]
vueAdmin-template 首页加载有502k感觉还是有些大呢

  static/js/vendor.84c8faa3775836251a12.js     735 kB       6  [emitted]  [big]  vendor

**Comment by PanJiaChen** [comment]
个人问题吧。实测没这么大。
![image](https://user-images.githubusercontent.com/8121621/38917299-f0c33c48-431c-11e8-9380-60b278374969.png)
开启了gzip还能更小。
